In [40]:
from  __future__ import print_function
import torch

In [41]:
# make a simple 5x4 matrix

x = torch.Tensor(5,4)
print(x)


1.00000e-19 *
  0.0000  1.0842  0.0000  1.0842
  0.0000  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000  0.0000
  0.0000  0.0000  0.0000  0.0000
[torch.FloatTensor of size 5x4]



In [42]:
# Randdomly initialized matrix
x = torch.rand(5,4)
print(x)


 0.8279  0.2494  0.9360  0.4095
 0.4523  0.0623  0.6327  0.8333
 0.7154  0.2328  0.7027  0.5982
 0.8434  0.7973  0.8574  0.6481
 0.4558  0.9925  0.9888  0.5318
[torch.FloatTensor of size 5x4]



In [43]:
print(x.size())
print("torch.Size is  however a tuple ")

torch.Size([5, 4])
torch.Size is  however a tuple 


In [44]:
y = torch.rand(5, 4)
print(x + y)


 1.3527  0.2853  1.8305  1.0669
 1.3825  0.8608  0.7175  1.4620
 0.9138  1.2007  1.4080  1.1309
 1.6843  1.1873  1.5777  1.0847
 0.4859  1.1659  1.1593  1.1505
[torch.FloatTensor of size 5x4]



In [45]:
print(torch.add(x, y))


 1.3527  0.2853  1.8305  1.0669
 1.3825  0.8608  0.7175  1.4620
 0.9138  1.2007  1.4080  1.1309
 1.6843  1.1873  1.5777  1.0847
 0.4859  1.1659  1.1593  1.1505
[torch.FloatTensor of size 5x4]



In [46]:
result = torch.Tensor(5, 4)
torch.add(x, y, out=result)
print(result)


 1.3527  0.2853  1.8305  1.0669
 1.3825  0.8608  0.7175  1.4620
 0.9138  1.2007  1.4080  1.1309
 1.6843  1.1873  1.5777  1.0847
 0.4859  1.1659  1.1593  1.1505
[torch.FloatTensor of size 5x4]



In [47]:
print(x[:, 1])


 0.2494
 0.0623
 0.2328
 0.7973
 0.9925
[torch.FloatTensor of size 5]



In [48]:
# Converting torch Tensor into a numpy Array
a = torch.ones(10)
a


 1
 1
 1
 1
 1
 1
 1
 1
 1
 1
[torch.FloatTensor of size 10]

In [49]:
b = a.numpy()
print(b)

[ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1.]


In [50]:
# Watch the numpy array
a.add_(1)
print(a)
print(b)


 2
 2
 2
 2
 2
 2
 2
 2
 2
 2
[torch.FloatTensor of size 10]

[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]


In [51]:
# Doing the opposite; convertihng numpy Array into a torch Tensor
import numpy as np
a = np.ones(10)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[ 2.  2.  2.  2.  2.  2.  2.  2.  2.  2.]

 2
 2
 2
 2
 2
 2
 2
 2
 2
 2
[torch.DoubleTensor of size 10]



In [52]:
if torch.cuda.is_available():
    x = x.cuda()
    y = y.cuda()
    x + y

## A bit on Autograd

In [53]:
from torch.autograd import Variable

In [54]:
x = Variable(torch.ones(3,3), requires_grad=True)
print(x)

Variable containing:
 1  1  1
 1  1  1
 1  1  1
[torch.FloatTensor of size 3x3]



In [55]:
y = x + 2
print(y)

Variable containing:
 3  3  3
 3  3  3
 3  3  3
[torch.FloatTensor of size 3x3]



In [56]:
print(y.grad_fn)
#why does this fail?

AttributeError: grad_fn

In [57]:
z = y*y*3
out = z.mean()
print(z, out)

Variable containing:
 27  27  27
 27  27  27
 27  27  27
[torch.FloatTensor of size 3x3]
 Variable containing:
 27
[torch.FloatTensor of size 1]



#### Gradients
Backprop with out.backward is same as out.backward(torch.Tensor([1,0]))

In [58]:
out.backward()

In [59]:
print(x.grad)

Variable containing:
 2  2  2
 2  2  2
 2  2  2
[torch.FloatTensor of size 3x3]



In [60]:
x = torch.randn(5)
x = Variable(x, requires_grad=True)
y = x*2
while y.data.norm()<1000:
    y = y*2
print(y)

Variable containing:
-1358.7740
  731.0142
  699.5322
 -524.8378
 -568.4971
[torch.FloatTensor of size 5]



In [61]:
gradients = torch.FloatTensor([0.1, 1.0, 0.0001])
y.backward(gradients)
print(x.grad)

Variable containing:
  51.2000
 512.0000
   0.0512
[torch.FloatTensor of size 3]



In [62]:
help(Variable)

Help on class Variable in module torch.autograd.variable:

class Variable(torch._C._VariableBase)
 |  Wraps a tensor and records the operations applied to it.
 |  
 |  Variable is a thin wrapper around a Tensor object, that also holds
 |  the gradient w.r.t. to it, and a reference to a function that created it.
 |  This reference allows retracing the whole chain of operations that
 |  created the data. If the Variable has been created by the user, its creator
 |  will be ``None`` and we call such objects *leaf* Variables.
 |  
 |  Since autograd only supports scalar valued function differentiation, grad
 |  size always matches the data size. Also, grad is normally only allocated
 |  for leaf variables, and will be always zero otherwise.
 |  
 |  Attributes:
 |      data: Wrapped tensor of any type.
 |      grad: Variable holding the gradient of type and location matching
 |          the ``.data``.  This attribute is lazily allocated and can't
 |          be reassigned.
 |      requires

## A bit on NN 

In [102]:
import torch
from torch.autograd import Variable
import torch.nn as nn
import torch.nn.functional as fxnl

class MyNN(nn.Module):
    def __init__(self):
        super(MyNN, self).__init__()
        self.conv1 = nn.Conv2d(1,6,5)
        self.conv2 = nn.Conv2d(6,16,5)
        # An affine operation y = Wx+b
        self.fc1 = nn.Linear(16*5*5, 120)
        self.fc2 = nn.Linear(120,84)
        self.fc3 = nn.Linear(84,10)
        
    def forward(self, x):
        # max pooling over a 2x2 window
        x = fxnl.max_pool2d(fxnl.relu(self.conv1(x)), (2,2))
        x= fxnl.max_pool2d(fxnl.relu(self.conv2(x)), 2)
        x= x.view(-1, self.num_flat_features(x))
        x = fxnl.relu(self.fc1(x))
        x = fxnl.relu(self.fc2(x))
        x = self.fc3(x)
        return x

    def num_flat_features(self, x):
        # all dimensions except the batch dimension
        size = x.size()[1:]
        num_features = 1
        for s in size:
            num_features *= s
        return num_features


net = MyNN()
print(net)          

MyNN (
  (conv1): Conv2d(1, 6, kernel_size=(5, 5), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(5, 5), stride=(1, 1))
  (fc1): Linear (400 -> 120)
  (fc2): Linear (120 -> 84)
  (fc3): Linear (84 -> 10)
)


#### Notes
All you need to do is define the forward function and backward function (this is where the gradients - you know the curvatures , or the steepest path to local minima are computed) is automatically defined for us by using autograd.
We can use any of the Tensor ops in the forward function

In [111]:
params = list(net.parameters())
print(len(params))
print(params[0].size())

10
torch.Size([6, 1, 5, 5])


In [112]:
# Input to the forward is autograd.Variable as is the output

input = Variable(torch.randn(1, 1, 32, 32))
output = net(input)
print(output)

Variable containing:
-0.0525  0.1221 -0.0390  0.0300  0.0151  0.0359 -0.0839 -0.1024 -0.1495 -0.0095
[torch.FloatTensor of size 1x10]



In [113]:
net.zero_grad()
output.backward(torch.randn(1, 10), retain_variables=True)
print("First backward of ", output)

First backward of  Variable containing:
-0.0525  0.1221 -0.0390  0.0300  0.0151  0.0359 -0.0839 -0.1024 -0.1495 -0.0095
[torch.FloatTensor of size 1x10]



## Summarizing

1. torch.Tensor: We create a multi-dimensional array with torch.Tensor
2. autograd.Variable: W2 wrapped a Tensor and recorded the history of ops applied to it.
3. nn.Module - We played with the Neural Network Module
4. nn.Parameter - This parameter is automatically registered as a parameter with helpers for moving then to gpu, loading etc
5. autograd.Function = This implemented forward and backward definitions of an autograd op.

So, all in all we defined a neural network AND we processed inputs and called it backward.
