In [1]:
import numpy as np

In [2]:
def get_hessenberg_form(A):
    """Get Upper Hessenberg Form by using Householder Reflector
    
    This function assume input matrix A as square matrix because we want to compute eigen value
    
    Args:
        A: input matrix of shape (m, m)
        
    Returns:
        H: upper hessenberg matrix of shape (m, m)
    """
    
    m = A.shape[0]
    H = np.copy(A)
    
    for k in range(m-2):
        # select column for reflection 
        x = H[k+1:m,k]  
        
        # compute normal vector
        v = np.sign(x[0]) * np.linalg.norm(x, ord=2) * np.eye(1, x.shape[0], 0) + x
        v /= np.linalg.norm(v, ord=2)
        
        # compute reflector matrix
        Q = np.eye(m)
        Q[k+1:m,k+1:m] = np.eye(m-k-1) - 2*v*v.T
        
        # similarity transform
        H = np.dot(np.dot(Q, H), Q.T) 
    
    return H

In [4]:
A = np.array([[1.,2,3,4],
             [4,5,6,7],
             [7,10,9,11],
             [1,4,12,-8]])

print (A)

[[ 1.  2.  3.  4.]
 [ 4.  5.  6.  7.]
 [ 7. 10.  9. 11.]
 [ 1.  4. 12. -8.]]


In [5]:
H = get_hessenberg_form(A)
print (H.astype(np.int32))

[[  1  -4   3   0]
 [ -8  17 -10   3]
 [  0  -9 -10   2]
 [  0   0  -1   0]]


In [6]:
print (np.linalg.eigvals(A))
print (np.linalg.eigvals(H)) # same eigen value with A

[ 22.39372019 -13.12905672  -1.673079    -0.59158448]
[ 22.39372019 -13.12905672  -1.673079    -0.59158448]


In [7]:
def hessenberg_qr(H):
    """QR iteration using givens rotation
    
    Args:
        H: upper hessenberg matrix of shape (m, m)
        
    Returns:
        H_new: new upper hessenberg matrix of shape (m, m)
    """
    
    m = H.shape[0]
    R = np.copy(H)
    
    Qs = []
    # Q3*Q2*Q1*H = R
    for k in range(m-1):
        # select two indices for rotation
        xi = R[k,k]
        xj = R[k+1,k]
        
        # compute rotation matrix
        norm = np.sqrt(xi**2 + xj**2)
        cos = xi / norm
        sin = - xj / norm
        rot = np.array([[cos, -sin],
                        [sin, cos]])
        
        Q = np.eye(m)
        Q[k:k+2, k:k+2] = rot
        Qs.append(Q)
        
        R = np.dot(Q, R)
    
    # similarity transform with R * Q1^T * Q2^T * Q3^T = H_new
    for k in range(m-1):
        if k==0:
            H_new = np.dot(R, Qs[k].T)
        else:
            H_new = np.dot(H_new, Qs[k].T)

    return H_new

In [8]:
for i in range(10):
    H_new = hessenberg_qr(H)
    print ('\n%d 번째 qr iteration 결과' %(i+1))
    print (H_new.astype(np.int32))
    
    H = H_new


1 번째 qr iteration 결과
[[ 18 -11   4  -2]
 [ -9 -10   0  -2]
 [  0  -4   0   0]
 [  0   0   0   0]]

2 번째 qr iteration 결과
[[ 21  -5  -2   0]
 [ -6 -12   5   2]
 [  0   0  -1   0]
 [  0   0   0   0]]

3 번째 qr iteration 결과
[[ 21  -5   4  -1]
 [ -3 -12   5  -2]
 [  0   0  -1   0]
 [  0   0   0   0]]

4 번째 qr iteration 결과
[[ 22  -1  -3   0]
 [ -2 -13   5   2]
 [  0   0  -1   0]
 [  0   0   0   0]]

5 번째 qr iteration 결과
[[ 22  -2   4   0]
 [ -1 -13   5  -1]
 [  0   0  -1   0]
 [  0   0   0   0]]

6 번째 qr iteration 결과
[[ 22   0  -3   0]
 [  0 -13   5   1]
 [  0   0  -1   0]
 [  0   0   0   0]]

7 번째 qr iteration 결과
[[ 22  -1   4   0]
 [  0 -13   5  -1]
 [  0   0  -1   0]
 [  0   0   0   0]]

8 번째 qr iteration 결과
[[ 22   0  -3   0]
 [  0 -13   5   1]
 [  0   0  -1   0]
 [  0   0   0   0]]

9 번째 qr iteration 결과
[[ 22  -1   4   0]
 [  0 -13   5  -1]
 [  0   0  -1   0]
 [  0   0   0   0]]

10 번째 qr iteration 결과
[[ 22   1  -3   0]
 [  0 -13   5   1]
 [  0   0  -1   0]
 [  0   0   0   0]]


In [9]:
print(H)

[[ 2.23964345e+01  1.01162895e+00 -3.99289689e+00 -8.64584027e-01]
 [-9.53185822e-02 -1.31317710e+01  5.71184329e+00  1.95731776e+00]
 [ 4.56904318e-16 -2.49934586e-08 -1.67305884e+00 -7.92295866e-01]
 [ 1.34398419e-15 -5.60119902e-16 -2.75027919e-05 -5.91604624e-01]]


In [10]:
print (np.linalg.eigvals(A))
print (np.linalg.eigvals(H)) # same eigen value with A

[ 22.39372019 -13.12905672  -1.673079    -0.59158448]
[ 22.39372019 -13.12905672  -1.673079    -0.59158448]
