In [1]:
import tensorflow as tf

/Users/tarrysingh/anaconda/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


## Eager Execution

Eager execution is an experimental interface to TensorFlow that provides an imperative programming style (à la, Torch7, NumPy). When you enable eager execution, TensorFlow operations execute immediately; you do not execute a pre-constructed graph with `Session.run()`.

### Currently we're doing this... 

In [6]:
x = tf.placeholder(tf.float32, shape=[1, 1])
m = tf.matmul(x, x)

with tf.Session() as sess:
    print(sess.run(m, feed_dict={x: [[2.]]}))

[[ 4.]]


### Getting eager execution (warning! -- Don't try this stuff in your production systems!!)



In [7]:
!pip install tf-nightly

    100% |████████████████████████████████| 42.4MB 18kB/s  eta 0:00:01
    100% |████████████████████████████████| 2.9MB 260kB/s eta 0:00:01
    100% |████████████████████████████████| 81kB 6.7MB/s eta 0:00:01
    100% |████████████████████████████████| 61kB 5.3MB/s eta 0:00:01
    100% |████████████████████████████████| 102kB 5.9MB/s ta 0:00:01
  Running setup.py bdist_wheel for absl-py ... done
  Stored in directory: /Users/tarrysingh/Library/Caches/pip/wheels/8c/5e/39/0c9325dbacd131f31c14f84d3e0a492358e3cc729d0bc6f1bb
  Running setup.py bdist_wheel for futures ... done
  Stored in directory: /Users/tarrysingh/Library/Caches/pip/wheels/ad/79/48/b32521764d59b16fd1bc0ffd5862f6d3bf770c7d73ea1fb12a
Successfully built absl-py futures
Exception:
Traceback (most recent call last):
  File "/Users/tarrysingh/anaconda/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/tarrysingh/anaconda/lib/python3.6/site-packages/pip/command

### Fixed the above with the following (I hope!)

```shell
MacBook-Pro-2:~ tarrysingh$ sudo pip install tf-nightly
Password:
The directory '/Users/tarrysingh/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/tarrysingh/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting tf-nightly
  Downloading tf_nightly-1.5.0.dev20171122-cp36-cp36m-macosx_10_11_x86_64.whl (42.4MB)
    100% |████████████████████████████████| 42.4MB 18kB/s 
Requirement already satisfied: enum34>=1.1.6 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Collecting mock>=2.0.0 (from tf-nightly)
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 6.0MB/s 
Requirement already satisfied: protobuf>=3.4.0 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Collecting backports.weakref>=1.0rc1 (from tf-nightly)
  Downloading backports.weakref-1.0.post1-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10.0 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Requirement already satisfied: tb-nightly<1.6.0a0,>=1.5.0a0 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Requirement already satisfied: numpy>=1.12.1 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Requirement already satisfied: wheel>=0.26 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Collecting absl-py (from tf-nightly)
Collecting pbr>=0.11 (from mock>=2.0.0->tf-nightly)
  Downloading pbr-3.1.1-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 7.4MB/s 
Requirement already satisfied: setuptools in ./anaconda/lib/python3.6/site-packages (from protobuf>=3.4.0->tf-nightly)
Requirement already satisfied: werkzeug>=0.11.10 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Requirement already satisfied: markdown>=2.6.8 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Requirement already satisfied: html5lib==0.9999999 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Requirement already satisfied: futures>=3.1.1 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Requirement already satisfied: bleach==1.5.0 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Installing collected packages: pbr, mock, backports.weakref, absl-py, tf-nightly
Successfully installed absl-py-0.1.5 backports.weakref-1.0.post1 mock-2.0.0 pbr-3.1.1 tf-nightly-1.5.0.dev20171122
```


In [1]:
import tensorflow as tf
import tensorflow.contrib.eager as tfe

In [2]:
tfe.enable_eager_execution()

In [4]:
# multiple 3 X 3 matrix
x = tf.matmul([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]
              ],
              [
               [10, 11, 12],
               [13, 14, 15],
               [16, 17, 18],
              ])

In [5]:
# add one to each element using tf.add for broadcasting
y = tf.add(x, 1)

In [6]:
# Create a random random matrix
z = tf.random_uniform([6, 4])

In [7]:
print(x)

tf.Tensor(
[[ 84  90  96]
 [201 216 231]
 [318 342 366]], shape=(3, 3), dtype=int32)


In [8]:
print(y)

tf.Tensor(
[[ 85  91  97]
 [202 217 232]
 [319 343 367]], shape=(3, 3), dtype=int32)


In [9]:
print(z)

tf.Tensor(
[[ 0.47207558  0.70240712  0.07745922  0.35342956]
 [ 0.74914169  0.53220427  0.12502646  0.70724893]
 [ 0.01018655  0.76463735  0.61849976  0.54388297]
 [ 0.24877775  0.21197641  0.87039661  0.91248119]
 [ 0.26888895  0.27225351  0.40576231  0.69011891]
 [ 0.57791257  0.25492835  0.05408299  0.32339919]], shape=(6, 4), dtype=float32)


### Cool huh!

What you see isw that with eager execution enabled [**its experimental, so don't go about playing with it in production!**] there I said it again 😌