In [1]:
import tensorflow as tf

/Users/tarrysingh/anaconda/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


## Eager Execution

Eager execution is an experimental interface to TensorFlow that provides an imperative programming style (à la, Torch7, NumPy). When you enable eager execution, TensorFlow operations execute immediately; you do not execute a pre-constructed graph with `Session.run()`.

### Currently we're doing this... 

In [6]:
x = tf.placeholder(tf.float32, shape=[1, 1])
m = tf.matmul(x, x)

with tf.Session() as sess:
    print(sess.run(m, feed_dict={x: [[2.]]}))

[[ 4.]]


### Getting eager execution (warning! -- Don't try this stuff in your production systems!!)



In [7]:
!pip install tf-nightly

    100% |████████████████████████████████| 42.4MB 18kB/s  eta 0:00:01
    100% |████████████████████████████████| 2.9MB 260kB/s eta 0:00:01
    100% |████████████████████████████████| 81kB 6.7MB/s eta 0:00:01
    100% |████████████████████████████████| 61kB 5.3MB/s eta 0:00:01
    100% |████████████████████████████████| 102kB 5.9MB/s ta 0:00:01
  Running setup.py bdist_wheel for absl-py ... done
  Stored in directory: /Users/tarrysingh/Library/Caches/pip/wheels/8c/5e/39/0c9325dbacd131f31c14f84d3e0a492358e3cc729d0bc6f1bb
  Running setup.py bdist_wheel for futures ... done
  Stored in directory: /Users/tarrysingh/Library/Caches/pip/wheels/ad/79/48/b32521764d59b16fd1bc0ffd5862f6d3bf770c7d73ea1fb12a
Successfully built absl-py futures
Exception:
Traceback (most recent call last):
  File "/Users/tarrysingh/anaconda/lib/python3.6/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/Users/tarrysingh/anaconda/lib/python3.6/site-packages/pip/command

### Fixed the above with the following (I hope!)

```shell
MacBook-Pro-2:~ tarrysingh$ sudo pip install tf-nightly
Password:
The directory '/Users/tarrysingh/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/tarrysingh/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting tf-nightly
  Downloading tf_nightly-1.5.0.dev20171122-cp36-cp36m-macosx_10_11_x86_64.whl (42.4MB)
    100% |████████████████████████████████| 42.4MB 18kB/s 
Requirement already satisfied: enum34>=1.1.6 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Collecting mock>=2.0.0 (from tf-nightly)
  Downloading mock-2.0.0-py2.py3-none-any.whl (56kB)
    100% |████████████████████████████████| 61kB 6.0MB/s 
Requirement already satisfied: protobuf>=3.4.0 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Collecting backports.weakref>=1.0rc1 (from tf-nightly)
  Downloading backports.weakref-1.0.post1-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10.0 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Requirement already satisfied: tb-nightly<1.6.0a0,>=1.5.0a0 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Requirement already satisfied: numpy>=1.12.1 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Requirement already satisfied: wheel>=0.26 in ./anaconda/lib/python3.6/site-packages (from tf-nightly)
Collecting absl-py (from tf-nightly)
Collecting pbr>=0.11 (from mock>=2.0.0->tf-nightly)
  Downloading pbr-3.1.1-py2.py3-none-any.whl (99kB)
    100% |████████████████████████████████| 102kB 7.4MB/s 
Requirement already satisfied: setuptools in ./anaconda/lib/python3.6/site-packages (from protobuf>=3.4.0->tf-nightly)
Requirement already satisfied: werkzeug>=0.11.10 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Requirement already satisfied: markdown>=2.6.8 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Requirement already satisfied: html5lib==0.9999999 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Requirement already satisfied: futures>=3.1.1 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Requirement already satisfied: bleach==1.5.0 in ./anaconda/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly)
Installing collected packages: pbr, mock, backports.weakref, absl-py, tf-nightly
Successfully installed absl-py-0.1.5 backports.weakref-1.0.post1 mock-2.0.0 pbr-3.1.1 tf-nightly-1.5.0.dev20171122
```


In [1]:
import tensorflow as tf
import tensorflow.contrib.eager as tfe

In [23]:
print(tf.__version__)

1.5.0-dev20171122


### We are playing with fire here. Version 1.5!!! 

In [2]:
tfe.enable_eager_execution()

In [4]:
# multiple 3 X 3 matrix
x = tf.matmul([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]
              ],
              [
               [10, 11, 12],
               [13, 14, 15],
               [16, 17, 18],
              ])

In [5]:
# add one to each element using tf.add for broadcasting
y = tf.add(x, 1)

In [6]:
# Create a random random matrix of, say 6 by 4 matrix
z = tf.random_uniform([6, 4])

In [7]:
print(x)

tf.Tensor(
[[ 84  90  96]
 [201 216 231]
 [318 342 366]], shape=(3, 3), dtype=int32)


In [8]:
print(y)

tf.Tensor(
[[ 85  91  97]
 [202 217 232]
 [319 343 367]], shape=(3, 3), dtype=int32)


In [9]:
print(z)

tf.Tensor(
[[ 0.47207558  0.70240712  0.07745922  0.35342956]
 [ 0.74914169  0.53220427  0.12502646  0.70724893]
 [ 0.01018655  0.76463735  0.61849976  0.54388297]
 [ 0.24877775  0.21197641  0.87039661  0.91248119]
 [ 0.26888895  0.27225351  0.40576231  0.69011891]
 [ 0.57791257  0.25492835  0.05408299  0.32339919]], shape=(6, 4), dtype=float32)


### Cool huh!

What you see is that with eager execution enabled, these ops consume and return multi-dimensional arrays as `Tensor` objects pretty much like what you see in `Torch` or `Numpy ndarray` or other imperative constructs.

[**its experimental, so don't go about playing with it in production!**] there I said it again 😌

These operations can also be triggered via operator overloading of the `Tensor` object.

Col thing is that you can use the `+` instead of tf.add, `-` for tf.subtract etc.

In [11]:
a = (tf.ones([1], dtype=tf.float32) + 1) *2 - 1
print(a)

tf.Tensor([ 3.], shape=(1,), dtype=float32)


In [12]:
a # here you get more info about the numpy array

<tf.Tensor: id=28, shape=(1,), dtype=float32, numpy=array([ 3.], dtype=float32)>

### Coverting to and from Numpy

This operations converts python objects to `Tensor` objects and vice versa.

In [13]:
import numpy as np

In [19]:
x = tf.add(1, 1)                             # tf.Tensor with a value of 2
y = tf.add(np.array(1), np.array(1))         # tf.Tensor w a value of 2
z = np.multiply(x, y)                        # numpu.int64 with a value of 4
print(x)
print(y)
print(z)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int64)
4


#### you can explicitly convert using...

`tf.constant` as you see next...

You can also call `numpy()` method of a `Tensor` object to obtain its Numpy `ndarray` value.

In [20]:
np_x = np.array(2., dtype=np.float32)
x = tf.constant(np_x)
py_y = 3.
y = tf.constant(py_y)

# add them up + 1

z = x + y + 1

print(z)
print(z.numpy())

tf.Tensor(6.0, shape=(), dtype=float32)
6.0


### CPU vs GPU acceleration and telling Eager Exec where to offload the computation

Easiest way to do this is to enclose your computation in ith a `tf.device('/gpu:0')` block. In case you have multiple GPUs, this function might come handy `tfe.num_gpus()`, that should return the number of GPUs you have on your cluster.

Here we multiply 1000 x 1000 matrices on a CPU:

In [21]:
import time

def measure(x):
  # The very first time a GPU is used by TensorFlow, it is initialized.
  # So exclude the first run from timing.
  tf.matmul(x, x)

  start = time.time()
  for i in range(10):
    tf.matmul(x, x)
  end = time.time()

  return "Took %s seconds to multiply a %s matrix by itself 10 times" % (end - start, x.shape)

# Run on CPU:
with tf.device("/cpu:0"):
  print("CPU: %s" % measure(tf.random_normal([1000, 1000])))

# If a GPU is available, run on GPU:
if tfe.num_gpus() > 0:
  with tf.device("/gpu:0"):
    print("GPU: %s" % measure(tf.random_normal([1000, 1000])))

CPU: Took 0.2117598056793213 seconds to multiply a (1000, 1000) matrix by itself 10 times


In [22]:
# you can copy Tensors to different devices

x = tf.random_normal([10, 10])

x_gpu0 = x.gpu()
x_cpu = x.cpu()

_ = tf.matmul(x_cpu, x_cpu) # will run this operation on CPU
_ = tf.matmul(x_gpu0, x_gpu0)# will run on your first GPU device, you can chang it to gpu1, gpu2 if you have many

if tfe.num_gpus() > 1:
    x_gpu1 = c.gpu()
    _ = tf.matmul(x_gpu1, x_gpu1)  # will run on your second GPU

RuntimeError: Error copying tensor to device: GPU:0. GPU:0 unknown device.

#### I get an error above since I don't have a GPU on my Mac 

##  Automatic Differentiation with Eager Execution

As per [Wikipedia](https://en.wikipedia.org/wiki/Automatic_differentiation):

In mathematics and computer algebra, automatic differentiation (AD), also called algorithmic differentiation or computational differentiation,[1][2] is a set of techniques to numerically evaluate the derivative of a function specified by a computer program. AD exploits the fact that every computer program, no matter how complicated, executes a sequence of elementary arithmetic operations (addition, subtraction, multiplication, division, etc.) and elementary functions (exp, log, sin, cos, etc.). By applying the chain rule repeatedly to these operations, derivatives of arbitrary order can be computed automatically, accurately to working precision, and using at most a small constant factor more arithmetic operations than the original program.

Automatic differentiation is not:
- Symbolic differentiation, nor
- Numerical differentiation (the method of finite differences).

These classical methods run into problems: symbolic differentiation leads to inefficient code (unless carefully done) and faces the difficulty of converting a computer program into a single expression, while numerical differentiation can introduce round-off errors in the discretization process and cancellation. Both classical methods have problems with calculating higher derivatives, where the complexity and errors increase. Finally, both classical methods are slow at computing the partial derivatives of a function with respect to many inputs, as is needed for gradient-based optimization algorithms. Automatic differentiation solves all of these problems, at the expense of introducing more software dependencies.

<img src="images/AutomaticDifferentiationNutshell.png">

**Automatic Differentiation** in TensorFlow is useful when implementing several deep learning algorithms. Eager Execution provides an autograd-like API for automatic differentiation, especially for functions such as these:

- `tfe.gradients_function(f)` : This returns a python function that computes the derivatives of the python function `f` w.r.t its arguments. `f` should return a scalr value. When invoeked this function returns a list of `Tensor` objects (an element for each argument of `f`)
- `tfe.value_and_gradients_function(f)` : Just like the above function this one returns , when invoked, the value of `f` in addition to the list of derivatives of `f` w.r.t its arguments.

Lets take a look how this works with an example:


In [ ]:
def f(x):
    return tf.multiply(x, x)
assert 9 == f(3.).numpy

# first order derivative

df = tfe.gradients_function(f)
assert 6 == df(3.)[0].numpy()

# second order derivative
d2f = tfe.gradients_function(lambda x:df(x)[0])
assert 2 == d2f(3.)[0]