# Step 0 : Upgrading to TensorFlow 1.4

### check your system requirements as per TensorFlow Documentation

For me this was good enough...

|Version:|	CPU/GPU:|	Python Version:|	Compiler:|	Build Tools:|	cuDNN:|	CUDA:|
--------|-----------|------------------|-------------|--------------|---------|------|
|tensorflow-1.4.0|	CPU|	2.7, 3.3-3.6|	GCC 4.8|	Bazel 0.5.4|	N/A|	N/A|
|tensorflow_gpu-1.4.0|	GPU|	2.7, 3.3-3.6|	GCC 4.8|	Bazel 0.5.4|	6|	8|
|tensorflow-1.3.0|	CPU|	2.7, 3.3-3.6|	GCC 4.8|	Bazel 0.4.5|	N/A	|N/A|
|tensorflow_gpu-1.3.0|	GPU|	2.7, 3.3-3.6|	GCC 4.8|	Bazel 0.4.5	|6|	8|

#### Check info for Bazel version

```shell
deeplearn@Ubuntu-1604-xenial-64-minimal:~$ bazel version
Build label: 0.5.4
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Fri Aug 25 10:00:00 2017 (1503655200)
Build timestamp: 1503655200
Build timestamp as int: 1503655200
```

#### Clone Tensorflow Git and switch to branch 1.4

```shell
deeplearn@Ubuntu-1604-xenial-64-minimal:~/downloads$ mkdir temp
deeplearn@Ubuntu-1604-xenial-64-minimal:~/downloads$ cd temp/
deeplearn@Ubuntu-1604-xenial-64-minimal:~/downloads/temp$ git clone https://github.com/tensorflow/tensorflow
Cloning into 'tensorflow'...
remote: Counting objects: 267022, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 267022 (delta 0), reused 0 (delta 0), pack-reused 267018
Receiving objects: 100% (267022/267022), 134.13 MiB | 24.28 MiB/s, done.
Resolving deltas: 100% (208394/208394), done.
deeplearn@Ubuntu-1604-xenial-64-minimal:~/downloads/temp$ cd tensorflow/
deeplearn@Ubuntu-1604-xenial-64-minimal:~/downloads/temp/tensorflow$ git checkout r
r0.10                     r0.8                      r1.2                      revert-14730-master 
r0.11                     r0.9                      r1.3                      revert-14765-patch-1 
r0.12                     r1.0                      r1.4                      
r0.7                      r1.1                      revert-14513-add_conv1d   
deeplearn@Ubuntu-1604-xenial-64-minimal:~/downloads/temp/tensorflow$ git checkout r
r0.10                     r0.8                      r1.2                      revert-14730-master 
r0.11                     r0.9                      r1.3                      revert-14765-patch-1 
r0.12                     r1.0                      r1.4                      
r0.7                      r1.1                      revert-14513-add_conv1d   
deeplearn@Ubuntu-1604-xenial-64-minimal:~/downloads/temp/tensorflow$ git checkout r1.
r1.0   r1.1   r1.2   r1.3   r1.4   
deeplearn@Ubuntu-1604-xenial-64-minimal:~/downloads/temp/tensorflow$ git checkout r1.4
Branch r1.4 set up to track remote branch r1.4 from origin.
Switched to a new branch 'r1.4'

```

#### Stay in the same directory and configure

```shell
deeplearn@Ubuntu-1604-xenial-64-minimal:~/downloads/temp/tensorflow$ ./configure 
You have bazel 0.5.4 installed.
Please specify the location of python. [Default is /home/deeplearn/anaconda3/bin/python]: 


Found possible Python library paths:
  /home/deeplearn/anaconda3/lib/python3.6/site-packages
Please input the desired Python library path to use.  Default is [/home/deeplearn/anaconda3/lib/python3.6/site-packages]

Do you wish to build TensorFlow with jemalloc as malloc support? [Y/n]: 
jemalloc as malloc support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Google Cloud Platform support? [Y/n]: n
No Google Cloud Platform support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Hadoop File System support? [Y/n]: 
Hadoop File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with Amazon S3 File System support? [Y/n]: 
Amazon S3 File System support will be enabled for TensorFlow.

Do you wish to build TensorFlow with XLA JIT support? [y/N]: 
No XLA JIT support will be enabled for TensorFlow.

Do you wish to build TensorFlow with GDR support? [y/N]: 
No GDR support will be enabled for TensorFlow.

Do you wish to build TensorFlow with VERBS support? [y/N]: 
No VERBS support will be enabled for TensorFlow.

Do you wish to build TensorFlow with OpenCL support? [y/N]: 
No OpenCL support will be enabled for TensorFlow.

Do you wish to build TensorFlow with CUDA support? [y/N]: y
CUDA support will be enabled for TensorFlow.

Please specify the CUDA SDK version you want to use, e.g. 7.0. [Leave empty to default to CUDA 8.0]: 


Please specify the location where CUDA 8.0 toolkit is installed. Refer to README.md for more details. [Default is /usr/local/cuda]: 


Please specify the cuDNN version you want to use. [Leave empty to default to cuDNN 6.0]: 


Please specify the location where cuDNN 6 library is installed. Refer to README.md for more details. [Default is /usr/local/cuda]:


Please specify a list of comma-separated Cuda compute capabilities you want to build with.
You can find the compute capability of your device at: https://developer.nvidia.com/cuda-gpus.
Please note that each additional compute capability significantly increases your build time and binary size. [Default is: 6.1]


Do you want to use clang as CUDA compiler? [y/N]: 
nvcc will be used as CUDA compiler.

Please specify which gcc should be used by nvcc as the host compiler. [Default is /usr/bin/gcc]: 


Do you wish to build TensorFlow with MPI support? [y/N]: 
No MPI support will be enabled for TensorFlow.

Please specify optimization flags to use during compilation when bazel option "--config=opt" is specified [Default is -march=native]: 


Add "--config=mkl" to your bazel command to build with MKL support.
Please note that MKL on MacOS or windows is still not supported.
If you would like to use a local MKL instead of downloading, please set the environment variable "TF_MKL_ROOT" every time before build.
Configuration finished


```

#### Build with Bazel

```shell
deeplearn@Ubuntu-1604-xenial-64-minimal:~/downloads/temp/tensorflow$ bazel build --config=opt --config=cuda //tensorflow/tools/pip_package:build_pip_package 
.......
WARNING: /home/deeplearn/downloads/temp/tensorflow/tensorflow/core/BUILD:1781:1: in includes attribute of cc_library rule //tensorflow/core:framework_headers_lib: '../../external/nsync/public' resolves to 'external/nsync/public' not below the relative path of its package 'tensorflow/core'. This will be an error in the future. Since this rule was created by the macro 'cc_header_only_library', the error might have been caused by the macro implementation in /home/deeplearn/downloads/temp/tensorflow/tensorflow/tensorflow.bzl:1044:30
WARNING: /home/deeplearn/downloads/temp/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:exporter': No longer supported. Switch to SavedModel immediately.
WARNING: /home/deeplearn/downloads/temp/tensorflow/tensorflow/contrib/learn/BUILD:15:1: in py_library rule //tensorflow/contrib/learn:learn: target '//tensorflow/contrib/learn:learn' depends on deprecated target '//tensorflow/contrib/session_bundle:gc': No longer supported. Switch to SavedModel immediately.
INFO: Analysed target //tensorflow/tools/pip_package:build_pip_package (205 packages loaded).
INFO: Found 1 target...
INFO: From Compiling external/snappy/snappy-c.cc [for host]:
.
.
.
.
.
.
        ^
Target //tensorflow/tools/pip_package:build_pip_package up-to-date:
  bazel-bin/tensorflow/tools/pip_package/build_pip_package
INFO: Elapsed time: 1507.903s, Critical Path: 120.82s
INFO: Build completed successfully, 6006 total actions

```

#### Build the pip package to a /tmp folder

```shell
deeplearn@Ubuntu-1604-xenial-64-minimal:~/downloads/temp/tensorflow$  bazel-bin/tensorflow/tools/pip_package/build_pip_package /tmp/tensorflow_pkg
Thu Nov 23 22:29:59 CET 2017 : === Using tmpdir: /tmp/tmp.COfRom0W7d
~/downloads/temp/tensorflow/bazel-bin/tensorflow/tools/pip_package/build_pip_package.runfiles ~/downloads/temp/tensorflow
~/downloads/temp/tensorflow
/tmp/tmp.COfRom0W7d ~/downloads/temp/tensorflow
Thu Nov 23 22:30:00 CET 2017 : === Building wheel
warning: no files found matching '*.dll' under directory '*'
warning: no files found matching '*.lib' under directory '*'
warning: no files found matching '*.h' under directory 'tensorflow/include/tensorflow'
warning: no files found matching '*' under directory 'tensorflow/include/Eigen'
warning: no files found matching '*' under directory 'tensorflow/include/external'
warning: no files found matching '*.h' under directory 'tensorflow/include/google'
warning: no files found matching '*' under directory 'tensorflow/include/third_party'
warning: no files found matching '*' under directory 'tensorflow/include/unsupported'
~/downloads/temp/tensorflow
Thu Nov 23 22:30:11 CET 2017 : === Output wheel file is in: /tmp/tensorflow_pkg


```

#### Upgrade your installation to TensorFlow 1.4 😀

```shell
deeplearn@Ubuntu-1604-xenial-64-minimal:~$ pip install --upgrade /tmp/tensorflow_pkg/tensorflow-1.4.1-cp36-cp36m-linux_x86_64.whl 
Processing /tmp/tensorflow_pkg/tensorflow-1.4.1-cp36-cp36m-linux_x86_64.whl
Requirement already up-to-date: numpy>=1.12.1 in ./anaconda3/lib/python3.6/site-packages (from tensorflow==1.4.1)
Requirement already up-to-date: six>=1.10.0 in ./anaconda3/lib/python3.6/site-packages (from tensorflow==1.4.1)
Collecting wheel>=0.26 (from tensorflow==1.4.1)
  Downloading wheel-0.30.0-py2.py3-none-any.whl (49kB)
    100% |████████████████████████████████| 51kB 7.5MB/s 
Collecting protobuf>=3.3.0 (from tensorflow==1.4.1)
  Downloading protobuf-3.5.0.post1-py2.py3-none-any.whl (389kB)
    100% |████████████████████████████████| 389kB 2.9MB/s 
Collecting enum34>=1.1.6 (from tensorflow==1.4.1)
  Downloading enum34-1.1.6-py3-none-any.whl
Collecting tensorflow-tensorboard<0.5.0,>=0.4.0rc1 (from tensorflow==1.4.1)
  Downloading tensorflow_tensorboard-0.4.0rc3-py3-none-any.whl (1.7MB)
    100% |████████████████████████████████| 1.7MB 996kB/s 
Collecting setuptools (from protobuf>=3.3.0->tensorflow==1.4.1)
  Downloading setuptools-37.0.0-py2.py3-none-any.whl (481kB)
    100% |████████████████████████████████| 491kB 4.0MB/s 
Collecting html5lib==0.9999999 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow==1.4.1)
Collecting bleach==1.5.0 (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow==1.4.1)
  Downloading bleach-1.5.0-py2.py3-none-any.whl
Requirement already up-to-date: werkzeug>=0.11.10 in ./anaconda3/lib/python3.6/site-packages (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow==1.4.1)
Requirement already up-to-date: markdown>=2.6.8 in ./anaconda3/lib/python3.6/site-packages (from tensorflow-tensorboard<0.5.0,>=0.4.0rc1->tensorflow==1.4.1)
Installing collected packages: wheel, setuptools, protobuf, enum34, html5lib, bleach, tensorflow-tensorboard, tensorflow
  Found existing installation: wheel 0.29.0
    Uninstalling wheel-0.29.0:
      Successfully uninstalled wheel-0.29.0
  Found existing installation: setuptools 36.6.0
    Uninstalling setuptools-36.6.0:
      Successfully uninstalled setuptools-36.6.0
  Found existing installation: protobuf 3.4.0
    Uninstalling protobuf-3.4.0:
      Successfully uninstalled protobuf-3.4.0
  Found existing installation: html5lib 1.0b10
    Uninstalling html5lib-1.0b10:
      Successfully uninstalled html5lib-1.0b10
  Found existing installation: bleach 2.1.1
    Uninstalling bleach-2.1.1:
      Successfully uninstalled bleach-2.1.1
  Found existing installation: tensorflow-tensorboard 0.1.5
    Uninstalling tensorflow-tensorboard-0.1.5:
      Successfully uninstalled tensorflow-tensorboard-0.1.5
  Found existing installation: tensorflow 1.3.0
    Uninstalling tensorflow-1.3.0:
      Successfully uninstalled tensorflow-1.3.0
Successfully installed bleach-1.5.0 enum34-1.1.6 html5lib-0.9999999 protobuf-3.5.0.post1 setuptools-37.0.0 tensorflow-1.4.1 tensorflow-tensorboard-0.4.0rc3 wheel-0.30.0

```

#### Finally, lets check if we're done?

###  Google's protobuf 3.5.0.post1 was giving me trouble

So I uninstalled and solved it by uninstalling 3.5.0.post1, installing previous release 3.4.0 and then installing 3.5.0.post1 again.

See my solution on [Github/Tensorflow] doc(https://github.com/tensorflow/tensorflow/issues/14689)

Here's what I did (raw stuff):

```shell
deeplearn@Ubuntu-1604-xenial-64-minimal:~$ pip uninstall protobuf
Uninstalling protobuf-3.5.0.post1:
  /home/deeplearn/anaconda3/lib/python3.6/site-packages/google/protobuf/__init__.py
  /home/deeplearn/anaconda3/lib/python3.6/site-packages/google/protobuf/__pycache__/__init__.cpython-36.pyc
  .
  .
  .
  .
  /home/deeplearn/anaconda3/lib/python3.6/site-packages/protobuf-3.5.0.post1.dist-info/top_level.txt
Proceed (y/n)? y
  Successfully uninstalled protobuf-3.5.0.post1
  
deeplearn@Ubuntu-1604-xenial-64-minimal:~$ pip install protobuf==3.5.0
Collecting protobuf==3.5.0
  Could not find a version that satisfies the requirement protobuf==3.5.0 (from versions: 2.0.0b0, 2.0.3, 2.3.0, 2.4.1, 2.5.0, 2.6.0, 2.6.1, 3.0.0a2, 3.0.0a3, 3.0.0b1, 3.0.0b1.post1, 3.0.0b1.post2, 3.0.0b2, 3.0.0b2.post1, 3.0.0b2.post2, 3.0.0b3, 3.0.0b4, 3.0.0, 3.1.0, 3.1.0.post1, 3.2.0rc1, 3.2.0rc1.post1, 3.2.0rc2, 3.2.0, 3.3.0, 3.4.0, 3.5.0.post1)
No matching distribution found for protobuf==3.5.0
deeplearn@Ubuntu-1604-xenial-64-minimal:~$ pip install protobuf==3.4.0
Requirement already satisfied: protobuf==3.4.0 in ./anaconda3/lib/python3.6/site-packages
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from protobuf==3.4.0)
Requirement already satisfied: six>=1.9 in ./anaconda3/lib/python3.6/site-packages (from protobuf==3.4.0)
deeplearn@Ubuntu-1604-xenial-64-minimal:~$ pip install protobuf==3.5.0.post1
Collecting protobuf==3.5.0.post1
  Using cached protobuf-3.5.0.post1-py2.py3-none-any.whl
Requirement already satisfied: six>=1.9 in ./anaconda3/lib/python3.6/site-packages (from protobuf==3.5.0.post1)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from protobuf==3.5.0.post1)
Installing collected packages: protobuf
  Found existing installation: protobuf 3.4.0
    Uninstalling protobuf-3.4.0:
      Successfully uninstalled protobuf-3.4.0
Successfully installed protobuf-3.5.0.post1

```



# Step 1 : Testing the installation

# Step 2: Getting the nightly build for eager execution / Upgrading to TensorFlow 1.5 OMG 😱

```shell
deeplearn@Ubuntu-1604-xenial-64-minimal:~$ pip install tf-nightly-gpu
Collecting tf-nightly-gpu
  Downloading tf_nightly_gpu-1.5.0.dev20171122-cp36-cp36m-manylinux1_x86_64.whl (121.7MB)
    100% |████████████████████████████████| 121.7MB 17kB/s 
Requirement already satisfied: wheel>=0.26 in ./anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu)
Requirement already satisfied: tb-nightly<1.6.0a0,>=1.5.0a0 in ./anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu)
Requirement already satisfied: numpy>=1.12.1 in ./anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu)
Requirement already satisfied: protobuf>=3.4.0 in ./anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu)
Requirement already satisfied: six>=1.10.0 in ./anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu)
Requirement already satisfied: absl-py in ./anaconda3/lib/python3.6/site-packages (from tf-nightly-gpu)
Requirement already satisfied: html5lib==0.9999999 in ./anaconda3/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly-gpu)
Requirement already satisfied: bleach==1.5.0 in ./anaconda3/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly-gpu)
Requirement already satisfied: futures>=3.1.1 in ./anaconda3/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly-gpu)
Requirement already satisfied: werkzeug>=0.11.10 in ./anaconda3/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly-gpu)
Requirement already satisfied: markdown>=2.6.8 in ./anaconda3/lib/python3.6/site-packages (from tb-nightly<1.6.0a0,>=1.5.0a0->tf-nightly-gpu)
Requirement already satisfied: setuptools in ./anaconda3/lib/python3.6/site-packages (from protobuf>=3.4.0->tf-nightly-gpu)
Installing collected packages: tf-nightly-gpu
Successfully installed tf-nightly-gpu-1.5.0.dev20171122

```

**Trying to execute eager execution** gave me this error (weird as I don't get it on my mac)

```shell

tfe.enable_eager_execution()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-9-cf53c6a364bc> in <module>()
----> 1 tfe.enable_eager_execution()

~/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py in enable_eager_execution(config, device_policy)
   4694     if graph_mode_has_been_used:
   4695       raise ValueError(
-> 4696           "tfe.enable_eager_execution has to be called at program startup.")
   4697   context._default_mode = context.EAGER_MODE
   4698   if context._context is None:

ValueError: tfe.enable_eager_execution has to be called at program startup.
```

In [1]:
import tensorflow as tf
import tensorflow.contrib.eager as tfe

/home/deeplearn/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
# solution is to bring down the protobuf version 
from google.protobuf import descriptor_pb2

In [2]:
print(tf.__version__)

1.5.0-dev20171122


In [3]:
tfe.enable_eager_execution()

In [8]:
# multiple 3 X 3 matrix
x = tf.matmul([[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]
              ],
              [
               [10, 11, 12],
               [13, 14, 15],
               [16, 17, 18],
              ])

In [9]:
# add one to each element using tf.add for broadcasting
y = tf.add(x, 1)

In [10]:
# Create a random random matrix of, say 6 by 4 matrix
z = tf.random_uniform([6, 4])

In [8]:
print(x) # This returned as per older situation without eager execution

Tensor("MatMul:0", shape=(3, 3), dtype=int32)


In [11]:
print(x) # printed with eager execution , you can see kept execution cell 8 as it is :)

tf.Tensor(
[[ 84  90  96]
 [201 216 231]
 [318 342 366]], shape=(3, 3), dtype=int32)


In [12]:
print(y)

tf.Tensor(
[[ 85  91  97]
 [202 217 232]
 [319 343 367]], shape=(3, 3), dtype=int32)


In [13]:
print(z)

tf.Tensor(
[[ 0.42166519  0.74874997  0.30295897  0.18815947]
 [ 0.13613379  0.41560864  0.78463495  0.76817131]
 [ 0.00482869  0.90712023  0.97884417  0.07941568]
 [ 0.85587406  0.86932099  0.58015025  0.09645569]
 [ 0.26412416  0.30468106  0.40509927  0.29306555]
 [ 0.57711077  0.2724632   0.35810065  0.68696404]], shape=(6, 4), dtype=float32)


### Cool huh!

What you see is that with eager execution enabled, these ops consume and return multi-dimensional arrays as `Tensor` objects pretty much like what you see in `Torch` or `Numpy ndarray` or other imperative constructs.

[**its experimental, so don't go about playing with it in production!**] there I said it again 😌

These operations can also be triggered via operator overloading of the `Tensor` object.

Col thing is that you can use the `+` instead of tf.add, `-` for tf.subtract etc.

In [14]:
a = (tf.ones([1], dtype=tf.float32) + 1) *2 - 1
print(a)

tf.Tensor([ 3.], shape=(1,), dtype=float32)


In [15]:
a # here you get more info about the numpy array

<tf.Tensor: id=30, shape=(1,), dtype=float32, numpy=array([ 3.], dtype=float32)>

### Coverting to and from Numpy

This operations converts python objects to `Tensor` objects and vice versa.

In [17]:
import numpy as np

In [18]:
x = tf.add(1, 1)                             # tf.Tensor with a value of 2
y = tf.add(np.array(1), np.array(1))         # tf.Tensor w a value of 2
z = np.multiply(x, y)                        # numpu.int64 with a value of 4
print(x)
print(y)
print(z)

tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int64)
4


#### you can explicitly convert using...

`tf.constant` as you see next...

You can also call `numpy()` method of a `Tensor` object to obtain its Numpy `ndarray` value.

In [20]:
np_x = np.array(2., dtype=np.float32)
x = tf.constant(np_x)
py_y = 3.
y = tf.constant(py_y)

# add them up + 1

z = x + y + 1

print(z)
print(z.numpy())

tf.Tensor(6.0, shape=(), dtype=float32)
6.0


### CPU vs GPU acceleration and telling Eager Exec where to offload the computation

Easiest way to do this is to enclose your computation in ith a `tf.device('/gpu:0')` block. In case you have multiple GPUs, this function might come handy `tfe.num_gpus()`, that should return the number of GPUs you have on your cluster.

Here we multiply 1000 x 1000 matrices on a CPU:

In [21]:
import time

def measure(x):
  # The very first time a GPU is used by TensorFlow, it is initialized.
  # So exclude the first run from timing.
  tf.matmul(x, x)

  start = time.time()
  for i in range(10):
    tf.matmul(x, x)
  end = time.time()

  return "Took %s seconds to multiply a %s matrix by itself 10 times" % (end - start, x.shape)

# Run on CPU:
with tf.device("/cpu:0"):
  print("CPU: %s" % measure(tf.random_normal([1000, 1000])))

# If a GPU is available, run on GPU:
if tfe.num_gpus() > 0:
  with tf.device("/gpu:0"):
    print("GPU: %s" % measure(tf.random_normal([1000, 1000])))

CPU: Took 0.17011046409606934 seconds to multiply a (1000, 1000) matrix by itself 10 times
GPU: Took 0.00032329559326171875 seconds to multiply a (1000, 1000) matrix by itself 10 times


In [22]:
# you can copy Tensors to different devices

x = tf.random_normal([10, 10])

x_gpu0 = x.gpu()
x_cpu = x.cpu()

_ = tf.matmul(x_cpu, x_cpu) # will run this operation on CPU
_ = tf.matmul(x_gpu0, x_gpu0)# will run on your first GPU device, you can chang it to gpu1, gpu2 if you have many

if tfe.num_gpus() > 1:
    x_gpu1 = c.gpu()
    _ = tf.matmul(x_gpu1, x_gpu1)  # will run on your second GPU

##  Automatic Differentiation with Eager Execution

As per [Wikipedia](https://en.wikipedia.org/wiki/Automatic_differentiation):

In mathematics and computer algebra, automatic differentiation (AD), also called algorithmic differentiation or computational differentiation,[1][2] is a set of techniques to numerically evaluate the derivative of a function specified by a computer program. AD exploits the fact that every computer program, no matter how complicated, executes a sequence of elementary arithmetic operations (addition, subtraction, multiplication, division, etc.) and elementary functions (exp, log, sin, cos, etc.). By applying the chain rule repeatedly to these operations, derivatives of arbitrary order can be computed automatically, accurately to working precision, and using at most a small constant factor more arithmetic operations than the original program.

Automatic differentiation is not:
- Symbolic differentiation, nor
- Numerical differentiation (the method of finite differences).

These classical methods run into problems: symbolic differentiation leads to inefficient code (unless carefully done) and faces the difficulty of converting a computer program into a single expression, while numerical differentiation can introduce round-off errors in the discretization process and cancellation. Both classical methods have problems with calculating higher derivatives, where the complexity and errors increase. Finally, both classical methods are slow at computing the partial derivatives of a function with respect to many inputs, as is needed for gradient-based optimization algorithms. Automatic differentiation solves all of these problems, at the expense of introducing more software dependencies.

<img src="images/AutomaticDifferentiationNutshell.png">

**Automatic Differentiation** in TensorFlow is useful when implementing several deep learning algorithms. Eager Execution provides an autograd-like API for automatic differentiation, especially for functions such as these:

- `tfe.gradients_function(f)` : This returns a python function that computes the derivatives of the python function `f` w.r.t its arguments. `f` should return a scalr value. When invoeked this function returns a list of `Tensor` objects (an element for each argument of `f`)
- `tfe.value_and_gradients_function(f)` : Just like the above function this one returns , when invoked, the value of `f` in addition to the list of derivatives of `f` w.r.t its arguments.

Lets take a look how this works with an example:


In [23]:
def f(x):
    return tf.multiply(x, x)  # Or x * x
assert 9 == f(3.).numpy()

df = tfe.gradients_function(f)
assert 6 == df(3.)[0].numpy()

# Second order deriviative.
d2f = tfe.gradients_function(lambda x : df(x)[0])
assert 2 == d2f(3.)[0].numpy()

# Third order derivative.
d3f = tfe.gradients_function(lambda x : d2f(x)[0])
assert 0 == d3f(3.)[0].numpy()

AttributeError: 'NoneType' object has no attribute 'numpy'

In [24]:
def prediction(input, weight, bias):
    return input * weight + bias

# A toy dataset of points around 3 * x + 2
NUM_EXAMPLES = 1000
training_inputs = tf.random_normal([NUM_EXAMPLES])
noise = tf.random_normal([NUM_EXAMPLES])
training_outputs = training_inputs * 3 + 2 + noise

# A loss function: Mean-squared error
def loss(weight, bias):
    error = prediction(training_inputs, weight, bias) - training_outputs
    return tf.reduce_mean(tf.square(error))

# Function that returns the the derivative of loss with respect to
# weight and bias
grad = tfe.gradients_function(loss)

# Train for 200 steps (starting from some random choice for W and B, on the same
# batch of data).
W = 5.
B = 10.
learning_rate = 0.01
print("Initial loss: %f" % loss(W, B).numpy())
for i in range(200):
  (dW, dB) = grad(W, B)
  W -= dW * learning_rate
  B -= dB * learning_rate
  if i % 20 == 0:
    print("Loss at step %d: %f" % (i, loss(W, B).numpy()))
print("Final loss: %f" % loss(W, B).numpy())
print("W, B = %f, %f" % (W.numpy(), B.numpy()))

Initial loss: 68.281876
Loss at step 0: 65.645905
Loss at step 20: 30.064030
Loss at step 40: 14.059760
Loss at step 60: 6.859705
Loss at step 80: 3.619853
Loss at step 100: 2.161713
Loss at step 120: 1.505334
Loss at step 140: 1.209814
Loss at step 160: 1.076741
Loss at step 180: 1.016808
Final loss: 0.990712
W, B = 3.074969, 2.132225
