# Basic Programming and Mathematics Stuff

## Control Flow

- **Compound Expression**
- **Conditional Evaluation**
- **Short-Circuit Evaluation**
- **Loops or Repeated Evaluation**
- **Exeption Handling**
- **Tasks**

## Mathematics

- **Numbers**
- **Strings**
- ** Arrays**
- **Linear Algebra**

## Control Flow

The coolest things of control flow logic in newer programming languages is that things are being written elegantly in one line of code as compared to how we used to be punching hundreds of lines of code in Java or VB, back in the days.

### Compound Expressions...

... is one such way to do things.

In [1]:
a = begin
    x = 4
    y = 5
    z = 6
    x + y + z
end

15

In [3]:
# Or do it in one line of code using ";" to chain stuff
a = (x = 4; y = 5; z = 6; x + y + z)

15

In [5]:
# So, this syntax comes super handy when writing terse single-line functions
begin x = 4; y = 5; z = 6; x + y + z end

15

### Conditional Evaluation

This is our typical if, elseif (not elif like in Python but similar to SQL), other operators remain kind of intuitive as you may have used in the past. 

```Julia
if a > b
    println("a is greater than b")
elseif a < b
    println("a is smaller than b")
    else print("They seem to be equal, dude!")
end
```

In [7]:
function fxn_test(a, b)
    if a > b
    println("a is greater than b")
    elseif a < b
        println("a is smaller than b")
    else print("They seem to be equal, dude!")
    end
end

fxn_test (generic function with 1 method)

In [8]:
fxn_test(3, 4)

a is smaller than b


In [9]:
fxn_test(4, 4.0)

They seem to be equal, dude!

In [10]:
fxn_test(5, 4.99999999999)

a is greater than b


How about we throw in a **variable relation** and see how and where it fits in...

In [27]:
function fxn_test2(a, b)
    if a < b
        relation = "less than"
    elseif a == b
        relation = "equal to"
        else
        relation = "greater than"
    end
    println("a is ", relation, " b.")
end

fxn_test2 (generic function with 1 method)

In [28]:
fxn_test2(2, 3)

a is less than b.


In [29]:
fxn_test2(0/1, 0/1) # infinity is not really the best way to go.

a is equal to b.


In [35]:
x = 0

0

In [36]:
if x > 0
    "positive!"
    else 
    "negative!"
end

"negative!"

#### Unlike C, MATLAB, Perl, Python or Ruby -- but pretty much like Java, it throws an error...

-- if the value of a conditional expression is anything but true or false

In [37]:
if 1
    println("true")
end

LoadError: TypeError: non-boolean (Int64) used in boolean context

### Short-Circuit Evaluation

This is kind of similar to conditional evaluation. This type of behavior is found in programming languages having `&&` and `||` boolean operators.

Lets take a look how it behaves...

In [43]:
f(x) = (println(x); true)

f (generic function with 1 method)

In [44]:
g(x) = (println(x); false)

g (generic function with 1 method)

In [46]:
# OK, now with some numbers
f(4) && f(5)

4
5


true

In [47]:
f(4) && g(5)

4
5


false

In [48]:
g(4) && f(5)

4


false

In [51]:
g(4) && g(5)

4


false

In [53]:
f(4) || f(5)

4


true

In [54]:
f(4) || g(5)

4


true

In [55]:
g(4) || f(5)

4
5


true

In [56]:
g(4) || g(5)

4
5


false

In [57]:
function fact(n::Int)
    n >= 0 || erro("n must be a non-negative")
    n == 0 && return 1
    n * fact(n - 1)
end

fact (generic function with 1 method)

In [58]:
fact(5)

120

In [59]:
fact(0)

1

In [60]:
fact(-1)

LoadError: UndefVarError: erro not defined

In [61]:
# Boolean operations without short-circuit eval can be done with bitwise boolean operators
f(3) & g(5)

3
5


false

In [62]:
f(3) | g(5)

3
5


true

### Loops or Repeated Evaluations 

##### While loop

In [63]:
i = 10
while i <= 15
    println(i)
    i += 1 # same as i = i + 1, add 1 each time
end

10
11
12
13
14
15


##### For loop 

In [64]:
for i = 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [65]:
for i in [1, 5, 0]
    println(i)
end

1
5
0


In [66]:
# you can also use the ∈ sign

In [68]:
for j ∈ [1, 10, 0]
    println(j)
end

1
10
0


### Execption Handling 

In [69]:
# try and catch

f(x) = try
    sqrt(x)
catch
    sqrt(complex(x, 0))
end

f (generic function with 1 method)

In [70]:
f(5)

2.23606797749979

In [71]:
f(-1)

0.0 + 1.0im

In [72]:
f(1/0)

Inf

In [73]:
sqrt_second(x) = try
    sqrt(x[2])
    catch y
    if isa(y, DomainError)
        sqrt(complex(x[2], 0))
    elseif isa(y, BoundsError)
        sqrt(x)
    end
end

sqrt_second (generic function with 1 method)

In [76]:
sqrt_second([1 6])

2.449489742783178

In [77]:
# finally clauses

f = open("file")
try
    # do something on file
finally
    close(f)
end

LoadError: SystemError: opening file file: No such file or directory

## Mathematics

|Expression |	Name |	Description|
------------|--------|-------------|
|+x	        |unary plus |	the identity operation|
|-x	        |unary minus |	maps values to their additive inverses|
|x + y      |binary plus|	performs addition|
|x - y      |binary minus|	performs subtraction|
|x * y      |times|	performs multiplication|
|x / y      |divide|	performs division|
|x \ y      |inverse| divide	equivalent to y / x|
|x ^ y      |power|	raises x to the yth power|
|x % y      |remainder|	equivalent to rem(x,y)|

bitwise operators

|Expression |	Name |
------------|--------|
|~x	|bitwise not|
|x & y|	bitwise and|
|x | y|	bitwise or|
|x ⊻ y|	bitwise xor (exclusive or)|
|x >>> y|	logical shift right||
|x >> y|	arithmetic shift right|
|x << y|	logical/arithmetic shift lef|


In [80]:
# Vectorized Dot operations
[3,6,9] .^3

3-element Array{Int64,1}:
  27
 216
 729

##### Numeric comparisons

|Operator|	Name|
---------|------|
|==|	equality|
|!=, ≠|	inequality|
|<|	less than|
|<=, ≤|	less than or equal to|
|>|	greater than|
|>=, ≥|	greater than or equal to|


In [81]:
1 == 1

true

In [82]:
2 == 5

false

In [83]:
1 != 3 # like in SQL

true

In [85]:
NaN == NaN

false

In [86]:
NaN != NaN

true

In [88]:
Inf == Inf #Seriously?

true

| Function | Tests if|
----------|----------|
|isequal(x, y)|	x and y are identical|
|isfinite(x)|	x is a finite number|
|isinf(x)|	x is infinite|
|isnan(x)|	x is not a number|

In [89]:
isequal(NaN, NaN)

true

In [90]:
isequal(NaN, NaN32)

true

In [92]:
# chaining operations
 1 < 4 <= 4 < 5 == 5 > 2 >= 1 == 1 < 3 != 5

true

##### Operator precedence

| Category | Operators|
-----------|----------|
|Syntax	|. followed by ::|
|Exponentiation|	^|
|Fractions|	//|
|Multiplication|	 / % & \|
|Bitshifts|	<< >> >>>|
|Addition	|+ - | ⊻|
|Syntax|	: .. followed by |>|
|Comparisons|	> < >= <= == === != !== <:|
|Control flow|	&& followed by `||` followed by ?|
|Assignments|	= += -= *= /= //= \= ^= ÷= %= |= &= ⊻= <<= >>= >>>=

## Linear Algebra 

In [93]:
A = [1 2 3; 4 5 7; 8 9 11]

3×3 Array{Int64,2}:
 1  2   3
 4  5   7
 8  9  11

In [94]:
trace(A) # adds up diagonal elements of the matrix

17

In [95]:
det(A) # matrix determinant

4.000000000000007

In [96]:
inv(A) # inverses the matrix

3×3 Array{Float64,2}:
 -2.0   1.25  -0.25
  3.0  -3.25   1.25
 -1.0   1.75  -0.75

In [98]:
eigvals(A)

3-element Array{Float64,1}:
 18.3218  
 -1.12834 
 -0.193486

In [99]:
eigvecs(A)

3×3 Array{Float64,2}:
 -0.203549  -0.601971   0.362257
 -0.502609  -0.397888  -0.835607
 -0.84021    0.692326   0.412955

In [100]:
# Factorization 
A = [2.5 4 -5; 4 1 -6; -10 4.5 5]

3×3 Array{Float64,2}:
   2.5  4.0  -5.0
   4.0  1.0  -6.0
 -10.0  4.5   5.0

In [101]:
factorize(A)

Base.LinAlg.LU{Float64,Array{Float64,2}} with factors L and U:
[1.0 0.0 0.0; -0.25 1.0 0.0; -0.4 0.546341 1.0]
[-10.0 4.5 5.0; 0.0 5.125 -3.75; 0.0 0.0 -1.95122]

**NOTE**: Since this matrix isn't symmetric, triangular, triagonol or bidiagonal, it does an LU factorization.

In [102]:
B = [1.5 2 -4; 2 -1 -3; -4 -3 5]

3×3 Array{Float64,2}:
  1.5   2.0  -4.0
  2.0  -1.0  -3.0
 -4.0  -3.0   5.0

In [103]:
factorize(B)

Base.LinAlg.BunchKaufman{Float64,Array{Float64,2}}([-1.64286 0.142857 -0.8; 2.0 -2.8 -0.6; -4.0 -3.0 5.0], [1, 2, 3], 'U', true, false, 0)

**NOTE**: It figures out for the abovce matrix that is was symmtric and does a correct factorization for it.

In [104]:
# You can tag stuff as well
B = [1.5 2 -4; 2 -1 -3; -4 -3 5]
sB = Symmetric(B)

3×3 Symmetric{Float64,Array{Float64,2}}:
  1.5   2.0  -4.0
  2.0  -1.0  -3.0
 -4.0  -3.0   5.0

In [105]:
x = [1; 2; 3]

3-element Array{Int64,1}:
 1
 2
 3

In [107]:
sB\x

3-element Array{Float64,1}:
 -1.73913
 -1.1087 
 -1.45652

**NOTE**: `\` operator performs a linear solution.

(Cope/paste from original documentation)
-------------------------------------
Julia's parser provides convenient dispatch to specialized methods for the transpose of a matrix left-divided by a vector, or for the various combinations of transpose operations in matrix-matrix solutions. Many of these are further specialized for certain special matrix types. For example, A\B will end up calling `Base.LinAlg.A_ldiv_B!` while `A'\B` will end up calling `Base.LinAlg.Ac_ldiv_B`, even though we used the same left-division operator. This works for matrices too: `A.'\B.'` would call `Base.LinAlg.At_ldiv_Bt`. The left-division operator is pretty powerful and it's easy to write compact, readable code that is flexible enough to solve all sorts of systems of linear equations.

Special Matrices

Type | Description |
-----|-------------|
|[Hermitian](https://docs.julialang.org/en/stable/stdlib/linalg/#Base.LinAlg.Hermitian)|	[Hermitian matrix](https://en.wikipedia.org/wiki/Hermitian_matrix)|
|UpperTriangular|	Upper triangular matrix|
|LowerTriangular|	Lower triangular matrix|
|Tridiagonal|	Tridiagonal matrix|
|SymTridiagonal|	Symmetric tridiagonal matrix|
|Bidiagonal|	Upper/lower bidiagonal matrix|
|Diagonal|	Diagonal matrix|
|UniformScaling|	Uniform scaling operator|


Types of Factorization (in Julia)

|Type|	Description|
----|---------------|
|Cholesky|	Cholesky factorization|
|CholeskyPivoted|	Pivoted Cholesky factorization|
|LU|	LU factorization|
|LUTridiagonal|	LU factorization for Tridiagonal matrices|
|UmfpackLU|	LU factorization for sparse matrices (computed by UMFPack)|
|QR|	QR factorization|
|QRCompactWY|	Compact WY form of the QR factorization|
|QRPivoted|	Pivoted QR factorization|
|Hessenberg|	Hessenberg decomposition|
|Eigen|	Spectral decomposition|
|SVD|	Singular value decomposition|
|GeneralizedSVD|	Generalized SVD|

For all about Linear Algebra, go to the original [documentation](https://docs.julialang.org/en/stable/manual/linear-algebra/). 