```
             _
   _       _ _(_)_     |  A fresh approach to technical computing
  (_)     | (_) (_)    |  Documentation: https://docs.julialang.org
   _ _   _| |_  __ _   |  Type "?help" for help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 0.6.1 (2017-10-24 22:15 UTC)
 _/ |\__'_|_|_|\__'_|  |  Official http://julialang.org/ release
|__/                   |  x86_64-pc-linux-gnu

julia> Pkg.add("IJulia")
INFO: Initializing package repository /.julia/v0.6
INFO: Cloning METADATA from https://github.com/JuliaLang/METADATA.jl
INFO: Cloning cache of BinDeps from https://github.com/JuliaLang/BinDeps.jl.git
INFO: Cloning cache of Compat from https://github.com/JuliaLang/Compat.jl.git
INFO: Cloning cache of Conda from https://github.com/JuliaPy/Conda.jl.git
INFO: Cloning cache of IJulia from https://github.com/JuliaLang/IJulia.jl.git
INFO: Cloning cache of JSON from https://github.com/JuliaIO/JSON.jl.git
INFO: Cloning cache of MbedTLS from https://github.com/JuliaWeb/MbedTLS.jl.git
INFO: Cloning cache of SHA from https://github.com/staticfloat/SHA.jl.git
INFO: Cloning cache of URIParser from https://github.com/JuliaWeb/URIParser.jl.git
INFO: Cloning cache of ZMQ from https://github.com/JuliaInterop/ZMQ.jl.git
INFO: Installing BinDeps v0.6.0
INFO: Installing Compat v0.34.0
INFO: Installing Conda v0.7.0
INFO: Installing IJulia v1.6.2
INFO: Installing JSON v0.15.1
INFO: Installing MbedTLS v0.5.1
INFO: Installing SHA v0.5.1
INFO: Installing URIParser v0.2.0
INFO: Installing ZMQ v0.5.1
INFO: Building Conda
INFO: Building MbedTLS
Using system libraries...
INFO: Building ZMQ
WARNING: Compat.ASCIIString is deprecated, use String instead.
  likely near /.julia/v0.6/ZMQ/deps/build.jl:36
INFO: Building IJulia
INFO: Found Jupyter version 4.3.0: jupyter
INFO: Installing Julia kernelspec julia-0.6
[InstallKernelSpec] Installed kernelspec julia-0.6 in /.local/share/jupyter/kernels/julia-0.6
INFO: Package database updated

julia> using IJulia
INFO: Precompiling module IJulia.

julia> notebook()

```

**Then fire it up from you Jupyter Notebook**

## Simple Tests

In [20]:
10+15

25

In [21]:
80*14

1120

In [22]:
45^5

184528125

In [23]:
a = Vector{Vector{Float64}}(3)
a[1] = [1;2;3]
a[2] = [1;2]
a[3] = [3;4;5]
a

3-element Array{Array{Float64,1},1}:
 [1.0, 2.0, 3.0]
 [1.0, 2.0]     
 [3.0, 4.0, 5.0]

In [24]:
b = a
b[1] = [1;4;5]
a

3-element Array{Array{Float64,1},1}:
 [1.0, 4.0, 5.0]
 [1.0, 2.0]     
 [3.0, 4.0, 5.0]

## Control Flow 

In [25]:
for i=1:5
    println(i)
end

t = 0
while t < 5
    println(t)
    t += 1
end

school=:GRN

if school==:GRN
    print("Groningen")
else
    print("If not Groningen, go home coz the brainiest folks come from Groningen!")
end

1
2
3
4
5
0
1
2
3
4
Groningen

In [26]:
for i=1:2,j=2:4
    println(i*j)
end

2
3
4
4
6
8


### Simple Function Syntax 

In [27]:
f(x,y) = 2x+y

f (generic function with 1 method)

In [28]:
f(1,2)

4

In [29]:
# More fun stuff
f(x,y,z,w) = x+y+z+w
@time f(1,1,1,1)
@time f(1,1,1,1)
@time f(1,1,1,1)
@time f(1,1,1,1.0)
@time f(1,1,1,1.0)

  0.001409 seconds (292 allocations: 18.649 KiB)
  0.000001 seconds (4 allocations: 160 bytes)
  0.000001 seconds (3 allocations: 144 bytes)
  0.002049 seconds (831 allocations: 49.039 KiB)
  0.000001 seconds (4 allocations: 160 bytes)


4.0

### Vector operations 

**Note** : Unlike Python, here indexing starts with 1 :)

In [30]:
A = [3 5 7] # create a row vector

1×3 Array{Int64,2}:
 3  5  7

In [31]:
A[1] # Getting first element, like Python and R

3

In [32]:
A = [3;5;7] # with semi-colons you create a column vector

3-element Array{Int64,1}:
 3
 5
 7

In [33]:
# Change elements
A[1] = 35

35

In [34]:
A

3-element Array{Int64,1}:
 35
  5
  7

### Matrix stuff 

In [35]:
M = [1 5 7;9 11 13;15 17 19] # We use semi-colons to change rows, space is used to seperate cols

3×3 Array{Int64,2}:
  1   5   7
  9  11  13
 15  17  19

In [36]:
M[1,2] = 6767 # change element in first row, second column
M

3×3 Array{Int64,2}:
  1  6767   7
  9    11  13
 15    17  19

In [37]:
M' # simple way to transpose values using a single quote

3×3 Array{Int64,2}:
    1   9  15
 6767  11  17
    7  13  19

In [38]:
inv(M) # Inversing the matrix

3×3 Array{Float64,2}:
 -7.39317e-5   -0.791402      0.541513   
  0.000147863  -0.000529844   0.000308049
 -7.39317e-5    0.625265     -0.375154   

### Dictoinaries 

In [39]:
D = Dict("name" => "Tarry's Tuts", "Class" => "Julia Computing")

Dict{String,String} with 2 entries:
  "Class" => "Julia Computing"
  "name"  => "Tarry's Tuts"

In [40]:
D["name"]

"Tarry's Tuts"

In [41]:
D.count

2

### Strings 

In [42]:
txt = "Hi there, I am a string!"
println(txt[1])
println(txt.len)

H
24


In [43]:
txt[1] = "Oh" # We can't change them, once created!

LoadError: MethodError: no method matching setindex!(::String, ::String, ::Int64)

##  It's fun, right?

### Let's try more fun stuff like Strang Matrix Problem

In [44]:
N = 15
A = zeros(N, N)

for i in 1:N, j in 1:N
    abs(i-j) <= 1 && (A[i, j] += 1)
    i == j && (A[i, j] -= 3)
end

In [45]:
A

15×15 Array{Float64,2}:
 -2.0   1.0   0.0   0.0   0.0   0.0  …   0.0   0.0   0.0   0.0   0.0   0.0
  1.0  -2.0   1.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   1.0  -2.0   1.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   1.0  -2.0   1.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   1.0  -2.0   1.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   1.0  -2.0  …   0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   1.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      1.0   0.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0     -2.0   1.0   0.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0  …   1.0  -2.0   1.0   0.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   1.0  -2.0   1.0   0.0   0.0
  0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0   1.0  -2.0   1.0   0.0
 

In [46]:
# Factorial problem

function fxn_factorial(n)
    k = one(n)
    for i in 1:n
        k *= i
    end
    k
end

fxn_factorial (generic function with 1 method)

In [47]:
fxn_factorial(5)

120

In [48]:
fxn_factorial(big(30))

265252859812191058636308480000000

In [49]:
# Binomial Problem

function fxn_binomial(n, p)
    count = zero(n)
    U = rand(n)
    
    for i in 1:n
        U[i] < p && (count += 1)
    end
    count
end

fxn_binomial (generic function with 1 method)

In [50]:
fxn_binomial(10, 0.5)

7

In [51]:
my_bin = [fxn_binomial(10, 0.5) for j in 1:10]

10-element Array{Int64,1}:
 6
 5
 4
 3
 6
 4
 7
 5
 4
 6

### Monte Carlo pi Problem 

In [52]:
n = 10000000 # Trying higher value will throw your laptop into overdrive :)

count = 0
for i in 1:n
    u,v = 2rand(2) - 1
    d = sqrt(u^2 + v^2) # distance from the middle of the square
    d < 1 && (count += 1)
end

area_est = count / n

print(area_est * 4)

3.1417512

### Timeseries Generation 

In [3]:
! Pkg.add("Plots")

INFO: Cloning cache of ColorTypes from https://github.com/JuliaGraphics/ColorTypes.jl.git
INFO: Cloning cache of Colors from https://github.com/JuliaGraphics/Colors.jl.git
INFO: Cloning cache of Contour from https://github.com/JuliaGeometry/Contour.jl.git
INFO: Cloning cache of DataStructures from https://github.com/JuliaCollections/DataStructures.jl.git
INFO: Cloning cache of FixedPointNumbers from https://github.com/JuliaMath/FixedPointNumbers.jl.git
INFO: Cloning cache of Measures from https://github.com/JuliaGraphics/Measures.jl.git
INFO: Cloning cache of NaNMath from https://github.com/mlubin/NaNMath.jl.git
INFO: Cloning cache of PlotThemes from https://github.com/JuliaPlots/PlotThemes.jl.git
INFO: Cloning cache of PlotUtils from https://github.com/JuliaPlots/PlotUtils.jl.git
INFO: Cloning cache of Plots from https://github.com/JuliaPlots/Plots.jl.git
INFO: Cloning cache of RecipesBase from https://github.com/JuliaPlots/RecipesBase.jl.git
INFO: Cloning cache of Reexport from https

LoadError: MethodError: no method matching !(::Void)
Closest candidates are:
  !(::Base.##771#772) at deprecated.jl:852
  !(::Bool) at bool.jl:36
  !(::Function) at operators.jl:904
  ...

In [53]:
using Plots

alphas = [0.0, 0.5, 0.98]
T = 100

series = []
labels = []

for alpha in alphas
    x = zeros(T + 1)
    x[1] = 0.0
    for t in 1:T
        x[t+1] = alpha * x[t] + randn()
    end
    push!(series, x)
    push!(labels, "alpha = $alpha")
end

plot(series, label=reshape(labels,1,length(labels)),lw=3)

### Ok, we've seen some cool examples

**Let's see the status of the packages**

We're getting distracted but I just wanted to know what we have in place and what we need before we get-to-know-Julia a bit better.

In [5]:
! Pkg.status()

2 required packages:
 - IJulia                        1.6.2
 - Plots                         0.13.1
24 additional packages:
 - BinDeps                       0.6.0
 - ColorTypes                    0.6.5
 - Colors                        0.8.2
 - Compat                        0.34.0
 - Conda                         0.7.0
 - Contour                       0.4.0
 - DataStructures                0.7.2
 - FixedPointNumbers             0.4.3
 - JSON                          0.15.1
 - MbedTLS                       0.5.1
 - Measures                      0.1.0
 - NaNMath                       0.2.6
 - PlotThemes                    0.1.4
 - PlotUtils                     0.4.4
 - RecipesBase                   0.2.3
 - Reexport                      0.0.3
 - Requires                      0.4.3
 - SHA                           0.5.1
 - Showoff                       0.1.1
 - SpecialFunctions              0.3.4
 - StaticArrays                  0.6.4
 - StatsBase                     0.19.0
 - URIParser   

LoadError: MethodError: no method matching !(::Void)
Closest candidates are:
  !(::Base.##771#772) at deprecated.jl:852
  !(::Bool) at bool.jl:36
  !(::Function) at operators.jl:904
  ...

In [6]:
Pkg.installed()

Dict{String,VersionNumber} with 26 entries:
  "NaNMath"           => v"0.2.6"
  "Showoff"           => v"0.1.1"
  "FixedPointNumbers" => v"0.4.3"
  "Conda"             => v"0.7.0"
  "SHA"               => v"0.5.1"
  "PlotUtils"         => v"0.4.4"
  "ZMQ"               => v"0.5.1"
  "JSON"              => v"0.15.1"
  "StatsBase"         => v"0.19.0"
  "DataStructures"    => v"0.7.2"
  "ColorTypes"        => v"0.6.5"
  "Compat"            => v"0.34.0"
  "IJulia"            => v"1.6.2"
  "Plots"             => v"0.13.1"
  "Colors"            => v"0.8.2"
  "MbedTLS"           => v"0.5.1"
  "Measures"          => v"0.1.0"
  "StaticArrays"      => v"0.6.4"
  "RecipesBase"       => v"0.2.3"
  "BinDeps"           => v"0.6.0"
  "SpecialFunctions"  => v"0.3.4"
  "PlotThemes"        => v"0.1.4"
  "Contour"           => v"0.4.0"
  "Requires"          => v"0.4.3"
  "Reexport"          => v"0.0.3"
  ⋮                   => ⋮

In [7]:
Pkg.update()

INFO: Updating METADATA...
INFO: Computing changes...
INFO: No packages to install, update or remove


## Cool ,so lets play around in our next Julia notebook with a few things like

- Control Flow (compound expression, conditional evaluation, Short-circuit evaluation etc)
- Math Stuff such as : Numbers, Strings, Arrays (Multi-dimensional as well) and ofcourse our lovely Linear Algebra