# NumPy: creating and manipulating numerical data 

## What is NumPy and numpy arrays

**Python:** - has built-in
- containers (costless insertion and append), dictionnaries (fast lookup)
- high-level number objects (integers, floating points)

**NumPy** is:
- extension package to Python to multidimensional arrays
- faster (as you'll see below)
- convenient and tested by scientific community

In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [4]:
l = range(1000)

%timeit [i**2 for i in l]

353 µs ± 2.58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
a = np.arange(1000)
%timeit a**2

1.52 µs ± 15.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [11]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

In [12]:
help(np.lookfor)

Help on function lookfor in module numpy.lib.utils:

lookfor(what, module=None, import_modules=True, regenerate=False, output=None)
    Do a keyword search on docstrings.
    
    A list of of objects that matched the search is displayed,
    sorted by relevance. All given keywords need to be found in the
    docstring for it to be returned as a result, but the order does
    not matter.
    
    Parameters
    ----------
    what : str
        String containing words to look for.
    module : str or list, optional
        Name of module(s) whose docstrings to go through.
    import_modules : bool, optional
        Whether to import sub-modules in packages. Default is True.
    regenerate : bool, optional
        Whether to re-generate the docstring cache. Default is False.
    output : file-like, optional
        File-like object to write the output to. If omitted, use a pager.
    
    See Also
    --------
    source, info
    
    Notes
    -----
    Relevance is determined only ro

## Creating Arrays

### 1-Dimensional

In [13]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [14]:
a.ndim

1

In [15]:
a.shape

(4,)

In [16]:
len(a)

4

### 2-D, 3-D and more 

In [17]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
b.ndim

2

In [22]:
b.shape

(2, 3)

In [23]:
len(b)

2

In [25]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [26]:
c.shape

(2, 2, 1)

In [29]:
print("Number of dimensions in array c: ",c.ndim)

Number of dimensions in array c:  3


### Evenly spaced 

In [35]:
#Evenly spaced - notice how it always starts with 0 .. (n-1) and not 1!
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### or,  number of points using linspace 

In [31]:
# number of points
c = np.linspace(0, 1, 9) # start, end, number of points
c

array([ 0.   ,  0.125,  0.25 ,  0.375,  0.5  ,  0.625,  0.75 ,  0.875,  1.   ])

In [33]:
d = np.linspace(0, 1, 5, endpoint=False) # meaning it doesn't stop at 1.
d

array([ 0. ,  0.2,  0.4,  0.6,  0.8])

### Common arrays 

In [36]:
a = np.ones((3, 3)) # (3, 3) would be a tuple here
a

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [40]:
type(a)

numpy.ndarray

In [41]:
b = np.zeros((2 ,2))
b

array([[ 0.,  0.],
       [ 0.,  0.]])

In [42]:
c = np.eye(3) # An identity matrix
c

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [43]:
d = np.diag(np.array([1,2,3,4]))
d

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

### Random numbers 

In [77]:
e = np.random.rand(4) # uniform in [0, 1]
e

array([ 0.42638175,  0.71417744,  0.3370914 ,  0.17486232])

In [79]:
f = np.random.randn(4) #Gaussian
f
# type help(np.random.randn) to understand more

array([-1.25793493,  0.97254164, -0.25065458,  0.0813759 ])

In [81]:
np.random.seed(1234) #setting the random seed
help(np.random.seed)

Help on built-in function seed:

seed(...) method of mtrand.RandomState instance
    seed(seed=None)
    
    Seed the generator.
    
    This method is called when `RandomState` is initialized. It can be
    called again to re-seed the generator. For details, see `RandomState`.
    
    Parameters
    ----------
    seed : int or array_like, optional
        Seed for `RandomState`.
        Must be convertible to 32 bit unsigned integers.
    
    See Also
    --------
    RandomState



## Exercise 1

**Create an array that looks like this:**

$$x = 
\begin{bmatrix}
    1 & 1 & 1 & 1 \\
    1 & 1 & 1 & 1 \\
    5 & 6 & 7 & 8 \\
    2 & 6 & 4 & 7 \\
\end{bmatrix}\tag{1}$$ and, 

**another one** that looks like this:

$$y = 
\begin{bmatrix}
    0. & 0. & 0. & 0. & 0.\\
    7. & 0. & 0. & 0. & 0.\\
    0. & 8. & 0. & 0. & 0.\\
    0. & 0. & 9. & 0. & 0.\\
    0. & 0. & 0. & 10. & 0.\\
    0. & 0. & 0. & 0. & 11.\\
\end{bmatrix}\tag{2}$$

and lastly,

**create** this simple array

$$\begin{bmatrix}
    0. & 0. & 0. & 0. & 0.\\
    0. & 0. & 0. & 0. & 0.\\
    1. & 0. & 0. & 0. & 0.\\
    0. & 1. & 0. & 0. & 0.\\
    0. & 0. & 1. & 0. & 0.\\
    0. & 0. & 0. & 1. & 0.\\
\end{bmatrix}\tag{3}$$

In [68]:
help(np.eye)
help(np.diag)

Help on function eye in module numpy.lib.twodim_base:

eye(N, M=None, k=0, dtype=<class 'float'>)
    Return a 2-D array with ones on the diagonal and zeros elsewhere.
    
    Parameters
    ----------
    N : int
      Number of rows in the output.
    M : int, optional
      Number of columns in the output. If None, defaults to `N`.
    k : int, optional
      Index of the diagonal: 0 (the default) refers to the main diagonal,
      a positive value refers to an upper diagonal, and a negative value
      to a lower diagonal.
    dtype : data-type, optional
      Data-type of the returned array.
    
    Returns
    -------
    I : ndarray of shape (N,M)
      An array where all elements are equal to zero, except for the `k`-th
      diagonal, whose values are equal to one.
    
    See Also
    --------
    identity : (almost) equivalent function
    diag : diagonal 2-D array from a 1-D array specified by the user.
    
    Examples
    --------
    >>> np.eye(2, dtype=int)
    arra

## Solutions 

## Exercise 1, Solutions 1, 2, 3

**Hint**: use help(np.diag) for info

In [90]:
help(np.diag)

Help on function diag in module numpy.lib.twodim_base:

diag(v, k=0)
    Extract a diagonal or construct a diagonal array.
    
    See the more detailed documentation for ``numpy.diagonal`` if you use this
    function to extract a diagonal and wish to write to the resulting array;
    whether it returns a copy or a view depends on what version of numpy you
    are using.
    
    Parameters
    ----------
    v : array_like
        If `v` is a 2-D array, return a copy of its `k`-th diagonal.
        If `v` is a 1-D array, return a 2-D array with `v` on the `k`-th
        diagonal.
    k : int, optional
        Diagonal in question. The default is 0. Use `k>0` for diagonals
        above the main diagonal, and `k<0` for diagonals below the main
        diagonal.
    
    Returns
    -------
    out : ndarray
        The extracted diagonal or constructed diagonal array.
    
    See Also
    --------
    diagonal : Return specified diagonals.
    diagflat : Create a 2-D array with the 

### Exercise 1: Solution 1

In [92]:
a = np.ones((4, 4), dtype=int)
a[3, 1] = 6
a[2, 3] = 2

print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 2]
 [1 6 1 1]]


### Exercise 1: Solution 2

In [94]:
b = np.zeros((6, 5))
b[1:] = np.diag(np.arange(7,12))
b

array([[  0.,   0.,   0.,   0.,   0.],
       [  7.,   0.,   0.,   0.,   0.],
       [  0.,   8.,   0.,   0.,   0.],
       [  0.,   0.,   9.,   0.,   0.],
       [  0.,   0.,   0.,  10.,   0.],
       [  0.,   0.,   0.,   0.,  11.]])

### Exercise 1: Solution 3 

In [95]:
y = np.eye(6, 5, k=-2, dtype=float)
y

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.]])