## Basic operations

#### With Scalars

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [3]:
2**a

array([ 2,  4,  8, 16])

#### All arithmetics element-wise operation 

In [4]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])