# Numerical operations with Numpy

## 3.1 **Broadcasting**
## 3.2 **Array shape manipulation**
##  3.3 **Sorting data**
##  **Summary**
## **Exercises**


## 3.1 Broadcasting Operations

-  We just covered basic operations (add, multiple, square etc) such are element-wise but that works on arrays of same size
- **Broadcasting** comes handy when we are dealing with different shapes. This time, we'll explore a more advanced concept in numpy called broadcasting. 

- The term broadcasting describes how numpy treats arrays with different shapes during arithmetic operations. Subject to certain constraints, *the smaller array is "broadcast" across the larger array so that they have compatible shapes*. 
- Broadcasting provides a means of **vectorizing array operations** so that looping occurs in C instead of Python. It does this without making needless copies of data and usually leads to efficient algorithm implementations. There are also cases where broadcasting is a bad idea because it leads to inefficient use of memory that slows computation.
- In this little tutorial we will provide a gentle introduction to broadcasting with numerous examples ranging from simple to involved. 
- We will also go through a few examples of when to and when not to use boradcasting.



#### This example below shows how broadcasting works

<img src="figures/numpy_broadcasting.png">

#### Let's try to solve the above puzzle 

In [1]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [10]:
a = np.tile(np.arange(0, 40, 10), (3, 1))
a = a.T # transpose this
a

array([[ 0,  0,  0],
       [10, 10, 10],
       [20, 20, 20],
       [30, 30, 30]])

In [11]:
b = np.array([0, 1, 2])
b

array([0, 1, 2])

##### Now, we add these two

In [13]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

##### Ask yourself, why couldn't we add original `a` and `b` ?

## 3.2 Array Shape Manipulation

## 3.3 Sorting Data