# Numerical operations with Numpy

#### Elementwise operations
#### Basic reductions
#### Broadcasting
#### Array shape manipulation
#### Sorting data
#### Summary

## Basic operations


#### With Scalars

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [3]:
2**a

array([ 2,  4,  8, 16])

#### All arithmetics element-wise operation 

In [4]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [6]:
a*b

array([ 2.,  4.,  6.,  8.])

In [7]:
j = np.arange(10)
2**(j + 1) - j

array([   2,    3,    6,   13,   28,   59,  122,  249,  504, 1015])

#### ... and lets see how fast is Numpy compared to Python's in-built operations 

In [11]:
a = np.arange(10000)
%timeit a + 1

6.52 µs ± 219 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
p = range(10000)
%timeit [i + 1 for i in p]

684 µs ± 5.29 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### Clearly, Numpy is winning hands down! 

Another thing about multiplication * VS matrix multiplication

In [13]:
c = np.ones((4,4))
c

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [14]:
c*c

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [21]:
np.dot(c, c)

array([[ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.]])

In [22]:
# Or you can simply do
c.dot(c)

array([[ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.]])

### More operations

#### Comparisions

In [28]:
a = np.array([1,2,3,4])
b = np.array([5,2,6,4])
c = np.array([1,2,3,4])

In [29]:
a == b

array([False,  True, False,  True], dtype=bool)

#### array-wise comparisons 

In [30]:
np.array_equal(a, b)

False

In [31]:
np.array_equal(a, c)

True

#### Logical operations 

In [37]:
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False], dtype=bool)

In [38]:
np.logical_and(a,b)

array([ True, False, False, False], dtype=bool)

In [39]:
np.logical_not(a,b)

array([False, False,  True,  True], dtype=bool)

In [40]:
np.logical_xor(a,b)

array([ True,  True,  True,  True], dtype=bool)

#### Trancendentaal functions: 

In [41]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [45]:
np.log(a)

/Users/tarrysingh/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436])

In [46]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

#### Shape mismatches: 

Throws a broacasting error. We'll get to that soon enough...

In [48]:
a = np.arange(5)
a + np.array([2,4])

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

#### Transposition. what is it?

In [52]:
a = np.triu(np.ones((4,4)), 1)
a

array([[ 0.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [53]:
a.T

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  0.]])

##### See, what happened above? 