# Numerical operations with Numpy

1.  **Elementwise operations**
2.  **Basic reductions**
3.  **Broadcasting**
4.  **Array shape manipulation**
5.  **Sorting data**
6.  **Summary**


## Elementwise Operations

### Basic Stuff


#### With Scalars

<img src="figures/dtype-hierarchy.png">

In [4]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a+1

array([2, 3, 4, 5])

In [3]:
2**a

array([ 2,  4,  8, 16])

#### All arithmetics element-wise operation 

In [4]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [6]:
a*b

array([ 2.,  4.,  6.,  8.])

In [7]:
j = np.arange(10)
2**(j + 1) - j

array([   2,    3,    6,   13,   28,   59,  122,  249,  504, 1015])

#### ... and lets see how fast is Numpy compared to Python's in-built operations 

In [11]:
a = np.arange(10000)
%timeit a + 1

6.52 µs ± 219 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [12]:
p = range(10000)
%timeit [i + 1 for i in p]

684 µs ± 5.29 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


#### Clearly, Numpy is winning hands down! 

Another thing about multiplication * VS matrix multiplication

In [13]:
c = np.ones((4,4))
c

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [14]:
c*c

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [21]:
np.dot(c, c)

array([[ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.]])

In [22]:
# Or you can simply do
c.dot(c)

array([[ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.],
       [ 4.,  4.,  4.,  4.]])

## More operations

### Comparisions

In [28]:
a = np.array([1,2,3,4])
b = np.array([5,2,6,4])
c = np.array([1,2,3,4])

In [29]:
a == b

array([False,  True, False,  True], dtype=bool)

#### array-wise comparisons 

In [30]:
np.array_equal(a, b)

False

In [31]:
np.array_equal(a, c)

True

#### Logical operations 

In [37]:
a = np.array([1,1,0,0], dtype=bool)
b = np.array([1,0,1,0], dtype=bool)
np.logical_or(a,b)

array([ True,  True,  True, False], dtype=bool)

In [38]:
np.logical_and(a,b)

array([ True, False, False, False], dtype=bool)

In [39]:
np.logical_not(a,b)

array([False, False,  True,  True], dtype=bool)

In [40]:
np.logical_xor(a,b)

array([ True,  True,  True,  True], dtype=bool)

#### Trancendentaal functions: 

In [41]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [45]:
np.log(a)

/Users/tarrysingh/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([       -inf,  0.        ,  0.69314718,  1.09861229,  1.38629436])

In [46]:
np.exp(a)

array([  1.        ,   2.71828183,   7.3890561 ,  20.08553692,  54.59815003])

#### Shape mismatches: 

Throws a broacasting error. We'll get to that soon enough...

In [48]:
a = np.arange(5)
a + np.array([2,4])

ValueError: operands could not be broadcast together with shapes (5,) (2,) 

#### Transposition. what is it?

In [52]:
a = np.triu(np.ones((4,4)), 1)
a

array([[ 0.,  1.,  1.,  1.],
       [ 0.,  0.,  1.,  1.],
       [ 0.,  0.,  0.,  1.],
       [ 0.,  0.,  0.,  0.]])

In [53]:
a.T

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  1.,  0.]])

##### See, what happened above? 

It flipped upside-down and then right-to-left

### Food for thought

- Look at np.allclose versus np.isclose. What is the difference between the two according to you?
- What is the difference between np.trui and np.tril?
- Also play with Ranges: How is np.linspace different than np.logspace?


## Basic reductions

### Calculating sums

In [5]:
x = np.array([5,6,7,8])
np.sum(x)

26

#### Adding by rows and by columns 

In [6]:
x = np.array([[2,2,], [6,6]])
x

array([[2, 2],
       [6, 6]])

In [7]:
x.sum(axis=0) #column-wise addition, first dimension

array([8, 8])

In [11]:
# more complex way to doing it, but you get the idea
x[:, 0].sum(), x[:, 1].sum()

(8, 8)

In [12]:
# Le's do row-wise
x.sum(axis=1)

array([ 4, 12])

In [13]:
x[0, :].sum(), x[1, :].sum()

(4, 12)

In [17]:
# In higher dimensions
x = np.random.rand(2,2,2)
x

array([[[ 0.59277357,  0.05258387],
        [ 0.63162507,  0.47989509]],

       [[ 0.48050849,  0.32805422],
        [ 0.08282492,  0.86972591]]])

In [18]:
x.sum(axis=2)[0, 1]

1.1115201595752902

In [19]:
# inspecting it more in detail
x[0, 1, :].sum()

1.1115201595752902

### Other forms of reductions

#### Extrema

In [20]:
x = np.array([2,5,6])
x.min()

2

In [21]:
x.max()

6

In [22]:
x.argmin() # Index of mimimum

0

In [23]:
x.argmax() # index of maximum

2

#### Logic Functions for Truth Value Testing

**Numpy.all**

`all(a[, axis, out, keepdims])`	Test whether all array elements along a given axis evaluate to True.

Try help(numpy.all) for more details.

In [26]:
np.all([True, True, False])

False

In [28]:
np.all([[True, True], [False, True]])

False

In [34]:
np.all([[True, True], [False, True]], axis=0) #axis=1 should give you the opposite result as you'll see

array([False,  True], dtype=bool)

In [35]:
np.all([-5, 4, 7])

True

In [36]:
np.all([1.0, np.nan])
# We'll get to np.nan - Not a number i.e; later

True

In [45]:
c = np.array([False])
d = np.all([-1, 4, 5], out=c, keepdims=True)
id(d), id(d), c

(4507411280, 4507411280, array([ True], dtype=bool))

#### Try the above operation with keepdims

What did you encounter? And why?



**Numpy.any**

`any(a[, axis, out, keepdims])`	Test whether any array element along a given axis evaluates to True.

In [48]:
np.any([True, True, False])

True

In [46]:
np.any([[True, False], [True, True]])

True

In [49]:
np.any([[True, False], [True, True]], axis=0)

array([ True,  True], dtype=bool)

In [50]:
np.any([-1, 0, 7])

True

In [53]:
np.any(np.nan)

True

In [55]:
c = np.array([False])
d = np.any([-1, 4, 5], out=c, keepdims=True)
id(d), id(d), c

(4506119824, 4506119824, array([ True], dtype=bool))

In [56]:
d is c

True

In [57]:
id(d), id(c)

(4506119824, 4506119824)

In [58]:
c

array([ True], dtype=bool)

In [62]:
# Can we try array comparisons?

a = np.zeros((200,200))

In [63]:
np.any(a != 0)

False

In [64]:
np.all( a == a)

True

In [68]:
a = np.array([3,4,5,6])
b = np.array([4,5,6,7])
c = np.array([6,7,3,2])
((a <= b) & (b <= c)).all() # np.all(((a <= b) & (b <= c)))

False

In [69]:
a <= b

array([ True,  True,  True,  True], dtype=bool)

In [70]:
b <= c

array([ True,  True, False, False], dtype=bool)

#### If we would have done `np.any()`...

What would then the answer be then?

In [78]:
((a <= b) & (b <= c)).any()

True

### Finite and Infinite

Test element-wise for finiteness and infinity

In [79]:
np.isfinite(1) # 1 is finite

True

In [88]:
np.isfinite(np.exp(100))

True

In [89]:
np.isfinite(np.exp(1000))

/Users/tarrysingh/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


False

In [85]:
np.exp(1000)

/Users/tarrysingh/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


inf

#### Above is a limitation of my computer...

The answer should actually be true...

...**but** if we do `np.isinf()'

In [90]:
np.isinf(np.exp(1000))

/Users/tarrysingh/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: overflow encountered in exp
  """Entry point for launching an IPython kernel.


True

In [91]:
np.isfinite(np.inf) # Kind of obvious as infinity is definitely NOT finite

False

In [93]:
np.isfinite([np.log(-1.), 1., np.log(0)]) # Trying same but in a different way...

/Users/tarrysingh/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in log
  """Entry point for launching an IPython kernel.
/Users/tarrysingh/anaconda/lib/python3.6/site-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([False,  True, False], dtype=bool)

#### How about `np.NINF` 

In [94]:
help(np.NINF)

Help on float object:

class float(object)
 |  float(x) -> floating point number
 |  
 |  Convert a string or number to a floating point number, if possible.
 |  
 |  Methods defined here:
 |  
 |  __abs__(self, /)
 |      abs(self)
 |  
 |  __add__(self, value, /)
 |      Return self+value.
 |  
 |  __bool__(self, /)
 |      self != 0
 |  
 |  __divmod__(self, value, /)
 |      Return divmod(self, value).
 |  
 |  __eq__(self, value, /)
 |      Return self==value.
 |  
 |  __float__(self, /)
 |      float(self)
 |  
 |  __floordiv__(self, value, /)
 |      Return self//value.
 |  
 |  __format__(...)
 |      float.__format__(format_spec) -> string
 |      
 |      Formats the float according to format_spec.
 |  
 |  __ge__(self, value, /)
 |      Return self>=value.
 |  
 |  __getattribute__(self, name, /)
 |      Return getattr(self, name).
 |  
 |  __getformat__(...) from builtins.type
 |      float.__getformat__(typestr) -> string
 |      
 |      You probably don't want to use thi

In [95]:
np.isfinite(np.NINF)

False

In [97]:
np.isfinite(np.nan) # Remember, NaN = Not is number

False

In [98]:
x = np.array([-np.inf, 0., np.inf])
y = np.array([2,2,2])
np.isfinite(x, y)

array([0, 1, 0])

In [99]:
x

array([-inf,   0.,  inf])

In [100]:
y

array([0, 1, 0])

## Statistics - A quick brush up

In [101]:
a = np.array([5,6,7,8])
b = np.array([[1,2,3], [4,5,6]])

In [103]:
# Doing a simple pythonic mean
a.mean()

6.5

In [104]:
np.mean(a) # Numpy gives the same value

6.5

In [105]:
np.median(a) # OK, same

6.5

In [109]:
# Let's do for b
np.median(b) 

3.5

In [118]:
# For last axis
np.median(b, axis=-1)

array([ 2.,  5.])

In [117]:
# for second last axis
np.median(b, axis=-2)

array([ 2.5,  3.5,  4.5])

#### Standard deviation


In [119]:
a.std()

1.1180339887498949

In [120]:
b.std()

1.707825127659933

In [121]:
np.std(a)

1.1180339887498949

In [146]:
c = np.array([[4,5], [8,9]])
np.std(c)

2.0615528128088303

In [147]:
c

array([[4, 5],
       [8, 9]])

In [148]:
np.std(c, axis=0)

array([ 2.,  2.])

In [149]:
np.std(c, axis=-1)

array([ 0.5,  0.5])

In [150]:
np.std(c, axis=1)

array([ 0.5,  0.5])

#### But standard can also be inaccurate... 

In [151]:
c = np.zeros((2, 256*256), dtype=np.float16)

In [152]:
c[0, :] = 1.0

In [153]:
c[1, :] = 0.1

In [154]:
np.std(d)

inf

##### What happened up there???

Now doing same with float32...

In [155]:
np.std(c, dtype=np.float32)

0.4500123

##### How about `np.float64`? 

In [156]:
np.std(c, dtype=np.float64)

0.45001220703125

##### `np.float128`?

In [157]:
np.std(c, dtype=np.float128)

0.45001220703125