# NumPy: creating and manipulating numerical data 

## What is NumPy and numpy arrays

**Python:** - has built-in
- containers (costless insertion and append), dictionnaries (fast lookup)
- high-level number objects (integers, floating points)

**NumPy** is:
- extension package to Python to multidimensional arrays
- faster (as you'll see below)
- convenient and tested by scientific community

In [1]:
import numpy as np

In [2]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [4]:
l = range(1000)

%timeit [i**2 for i in l]

353 µs ± 2.58 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [5]:
a = np.arange(1000)
%timeit a**2

1.52 µs ± 15.2 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [6]:
help(np.array)

Help on built-in function array in module numpy.core.multiarray:

array(...)
    array(object, dtype=None, copy=True, order='K', subok=False, ndmin=0)
    
    Create an array.
    
    Parameters
    ----------
    object : array_like
        An array, any object exposing the array interface, an object whose
        __array__ method returns an array, or any (nested) sequence.
    dtype : data-type, optional
        The desired data-type for the array.  If not given, then the type will
        be determined as the minimum type required to hold the objects in the
        sequence.  This argument can only be used to 'upcast' the array.  For
        downcasting, use the .astype(t) method.
    copy : bool, optional
        If true (default), then the object is copied.  Otherwise, a copy will
        only be made if __array__ returns a copy, if obj is a nested sequence,
        or if a copy is needed to satisfy any of the other requirements
        (`dtype`, `order`, etc.).
    order : {'K'

In [11]:
np.lookfor('create array')

Search results for 'create array'
---------------------------------
numpy.array
    Create an array.
numpy.memmap
    Create a memory-map to an array stored in a *binary* file on disk.
numpy.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.fromiter
    Create a new 1-dimensional array from an iterable object.
numpy.partition
    Return a partitioned copy of an array.
numpy.ctypeslib.as_array
    Create a numpy array from a ctypes array or a ctypes POINTER.
numpy.ma.diagflat
    Create a two-dimensional array with the flattened input as a diagonal.
numpy.ma.make_mask
    Create a boolean mask from an array.
numpy.ctypeslib.as_ctypes
    Create and return a ctypes object from a numpy array.  Actually
numpy.ma.mrecords.fromarrays
    Creates a mrecarray from a (flat) list of masked arrays.
numpy.ma.mvoid.__new__
    Create a new masked array from scratch.
numpy.lib.format.open_memmap
    Open a .npy file as a memory-mapped array.
numpy.ma.MaskedArr

In [12]:
help(np.lookfor)

Help on function lookfor in module numpy.lib.utils:

lookfor(what, module=None, import_modules=True, regenerate=False, output=None)
    Do a keyword search on docstrings.
    
    A list of of objects that matched the search is displayed,
    sorted by relevance. All given keywords need to be found in the
    docstring for it to be returned as a result, but the order does
    not matter.
    
    Parameters
    ----------
    what : str
        String containing words to look for.
    module : str or list, optional
        Name of module(s) whose docstrings to go through.
    import_modules : bool, optional
        Whether to import sub-modules in packages. Default is True.
    regenerate : bool, optional
        Whether to re-generate the docstring cache. Default is False.
    output : file-like, optional
        File-like object to write the output to. If omitted, use a pager.
    
    See Also
    --------
    source, info
    
    Notes
    -----
    Relevance is determined only ro

## Creating Arrays

### 1-Dimensional

In [13]:
a = np.array([0,1,2,3])
a

array([0, 1, 2, 3])

In [14]:
a.ndim

1

In [15]:
a.shape

(4,)

In [16]:
len(a)

4

### 2-D, 3-D and more 

In [17]:
b = np.array([[0, 1, 2], [3, 4, 5]])
b

array([[0, 1, 2],
       [3, 4, 5]])

In [20]:
b.ndim

2

In [22]:
b.shape

(2, 3)

In [23]:
len(b)

2

In [25]:
c = np.array([[[1], [2]], [[3], [4]]])
c

array([[[1],
        [2]],

       [[3],
        [4]]])

In [26]:
c.shape

(2, 2, 1)

In [29]:
print("Number of dimensions in array c: ",c.ndim)

Number of dimensions in array c:  3


#### Evenly spaced 

In [34]:
#Evenly spaced - notice how it always starts with 0 .. (n-1) and not 1!
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### or number of points using linspace 

In [31]:
# number of points
c = np.linspace(0, 1, 9) # start, end, number of points
c

array([ 0.   ,  0.125,  0.25 ,  0.375,  0.5  ,  0.625,  0.75 ,  0.875,  1.   ])

In [33]:
d = np.linspace(0, 1, 5, endpoint=False) # meaning it doesn't stop at 1.
d

array([ 0. ,  0.2,  0.4,  0.6,  0.8])